"""Guide/worker orchestration over one Local Work Trajectory slice.

This module builds the first scheduler-owned guide/worker workflow that can
plan worker tasks on trajectory lanes and run a bounded cross-lane wave.
Local Work Trajectory remains a projection/readback surface, not the authority.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Literal

from .artifact_paths import DEFAULT_DBC_SCRATCH_ROOT, dbc_artifact_path
from .exchange import (
    ExchangeArtifact,
    ExchangeCausality,
    ExchangeLog,
    ExchangePayloadPart,
    ExchangeReference,
    ExchangeScope,
    VisibilityPolicy,
)
from .exchange_admission_ledger import admit_exchange_artifact_version_with_ledger
from .exchange_store import InMemoryArtifactVersionStore, JsonArtifactVersionStore
from .preflight import (
    PreflightedTaskRunResult,
    build_orchestration_preflight_bundle,
    run_preflighted_task,
)
from .runtime_adapter import AgentRuntimeAdapterRegistry, AgentSpec, FakeAgentRuntimeAdapter
from .sandbox import SandboxProviderRegistry, SharedProcessSandboxProvider
from .scheduler import (
    ContextScope,
    EditScopeLease,
    SandboxProfile,
    SchedulerEvent,
    SchedulerEventSink,
    SchedulerState,
    TaskRunRecord,
    TaskDependency,
    mark_ready_tasks,
    wake_dependent_tasks,
)
from .scheduler_store import (
    JsonlSchedulerEventLog,
    read_scheduler_state_snapshot,
    write_scheduler_state_snapshot,
)
from .scheduler_submission import (
    SchedulerTaskBatchSubmission,
    SchedulerTaskSubmission,
    scheduler_task_batch_submission_to_artifact,
)

DEFAULT_GUIDE_WORKER_LOCAL_ORCHESTRATION_PREFIX = "guide-worker-local-orchestration"
DEFAULT_GUIDE_WORKER_LOCAL_ORCHESTRATION_SNAPSHOT_RELATIVE_PATH = (
    dbc_artifact_path("scheduler", "guide-worker-local-orchestration-state.json")
)
DEFAULT_GUIDE_WORKER_LOCAL_ORCHESTRATION_EVENT_LOG_RELATIVE_PATH = (
    dbc_artifact_path("scheduler", "guide-worker-local-orchestration-events.jsonl")
)

GuideWorkerWaveExecutionMode = Literal["serial", "threaded"]


@dataclass(frozen=True, slots=True)
class GuideWorkerInstruction:
    """One concrete worker instruction generated by the guide."""

    task_id: str
    title: str
    instruction: str
    lane_id: str
    context_id: str = ""
    worker_agent_id: str = ""
    worker_runtime_provider: str = ""
    allowed_artifacts: tuple[str, ...] = ()
    acceptance: tuple[str, ...] = ()
    depends_on_task_ids: tuple[str, ...] = ()
    output_artifact_id: str = ""
    sandbox_profile: SandboxProfile = field(
        default_factory=lambda: SandboxProfile(
            profile_id="shared-process",
            profile_kind="shared-process",
            network_policy="disabled",
            secret_policy="deny",
            mount_policy="lease-scoped",
        )
    )


@dataclass(frozen=True, slots=True)
class GuideWorkerPlannerLaneSpec:
    """One lane requested by the guide planner."""

    lane_id: str
    label: str
    focus: str
    allowed_artifacts: tuple[str, ...] = ()
    acceptance: tuple[str, ...] = ()
    depends_on_lane_ids: tuple[str, ...] = ()
    worker_agent_id: str = ""
    worker_runtime_provider: str = ""
    sandbox_profile: SandboxProfile = field(
        default_factory=lambda: SandboxProfile(
            profile_id="shared-process",
            profile_kind="shared-process",
            network_policy="disabled",
            secret_policy="deny",
            mount_policy="lease-scoped",
        )
    )


@dataclass(frozen=True, slots=True)
class GuideWorkerPlanningRequest:
    """High-level guide task description used to derive worker instructions."""

    task_title: str = ""
    task_summary: str = ""
    lane_specs: tuple[GuideWorkerPlannerLaneSpec, ...] = ()
    planner: str = "deterministic-lane-spec-v1"


@dataclass(frozen=True, slots=True)
class GuideWorkerParallelWave:
    """A deterministic cross-lane scheduling wave."""

    wave_id: str
    task_ids: tuple[str, ...]
    lane_ids: tuple[str, ...]
    execution_model: str = "scheduled_parallel_wave_sequential_fake_runtime"
    sequential_runtime: bool = True

    def to_json_dict(self) -> dict[str, object]:
        return {
            "wave_id": self.wave_id,
            "task_ids": list(self.task_ids),
            "lane_ids": list(self.lane_ids),
            "execution_model": self.execution_model,
            "sequential_runtime": self.sequential_runtime,
        }


@dataclass(frozen=True, slots=True)
class GuideWorkerWaveTaskRun:
    """One runtime invocation result inside a guide-worker wave."""

    task_id: str
    lane_id: str
    runtime_result: object | None = None
    error: str = ""

    @property
    def ok(self) -> bool:
        return self.runtime_result is not None and not self.error


@dataclass(frozen=True, slots=True)
class GuideWorkerWaveExecutionResult:
    """Result of executing one lane-distinct guide-worker scheduling wave."""

    wave: GuideWorkerParallelWave
    mode: GuideWorkerWaveExecutionMode
    attempted_task_ids: tuple[str, ...]
    completed_task_ids: tuple[str, ...]
    failed_task_ids: tuple[str, ...]
    deterministic_merge_order: tuple[str, ...]
    run_results: tuple[PreflightedTaskRunResult, ...]
    state: SchedulerState

    @property
    def ok(self) -> bool:
        return bool(self.attempted_task_ids) and not self.failed_task_ids

    @property
    def invoked_as_wave(self) -> bool:
        return len(self.attempted_task_ids) > 1

    def to_json_dict(self) -> dict[str, object]:
        return {
            "wave_id": self.wave.wave_id,
            "mode": self.mode,
            "attempted_task_ids": list(self.attempted_task_ids),
            "completed_task_ids": list(self.completed_task_ids),
            "failed_task_ids": list(self.failed_task_ids),
            "deterministic_merge_order": list(self.deterministic_merge_order),
            "invoked_as_wave": self.invoked_as_wave,
            "true_process_parallelism": self.mode == "threaded" and self.invoked_as_wave,
        }


@dataclass(frozen=True, slots=True)
class GuideWorkerLocalOrchestrationRequest:
    """Inputs for guide/worker local trajectory orchestration."""

    artifact_store_path: Path
    admission_ledger_path: Path
    snapshot_path: Path
    event_log_path: Path
    trajectory_id: str = "local-work:current"
    guide_agent_id: str = "agent:guide"
    worker_agent_id: str = "agent:worker"
    artifact_id_prefix: str = DEFAULT_GUIDE_WORKER_LOCAL_ORCHESTRATION_PREFIX
    timestamp: str = "2026-06-23T00:00:00Z"
    planning_request: GuideWorkerPlanningRequest = field(
        default_factory=GuideWorkerPlanningRequest
    )
    worker_instructions: tuple[GuideWorkerInstruction, ...] = ()
    max_parallel_lanes: int = 2
    max_waves: int = 1
    replace_existing: bool = False
    allow_duplicate_admission: bool = False
    workspace_root: str = ""
    scratch_root: str = DEFAULT_DBC_SCRATCH_ROOT
    wave_execution_mode: GuideWorkerWaveExecutionMode = "serial"


@dataclass(frozen=True, slots=True)
class GuideWorkerLocalOrchestrationResult:
    """Compact result of one guide/worker local trajectory orchestration run."""

    request: GuideWorkerLocalOrchestrationRequest
    guide_artifact_id: str
    guide_artifact_version: str
    scheduler_artifact_id: str
    scheduler_artifact_version: str
    submitted_task_ids: tuple[str, ...]
    lane_ids: tuple[str, ...]
    parallel_waves: tuple[GuideWorkerParallelWave, ...]
    planned_worker_instructions: tuple[GuideWorkerInstruction, ...] = ()
    planning_source: str = "default_planner"
    wave_execution_results: tuple[GuideWorkerWaveExecutionResult, ...] = ()
    run_results: tuple[PreflightedTaskRunResult, ...] = ()
    final_state: SchedulerState = field(default_factory=SchedulerState)
    admission_result: dict[str, object] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return bool(self.submitted_task_ids) and all(
            self.final_state.tasks.get(task_id) is not None
            and self.final_state.tasks[task_id].state == "complete"
            for task_id in self.submitted_task_ids
        )

    def to_json_dict(self) -> dict[str, object]:
        task_states = {
            task_id: task.state
            for task_id, task in sorted(self.final_state.tasks.items())
        }
        run_task_ids = tuple(result.preflight.task.task_id for result in self.run_results)
        worker_runtime_providers = tuple(
            dict.fromkeys(
                self.final_state.tasks[task_id].agent.runtime_provider
                for task_id in self.submitted_task_ids
                if task_id in self.final_state.tasks
            )
        )
        runtime_provider = (
            worker_runtime_providers[0]
            if len(worker_runtime_providers) == 1
            else "mixed"
        )
        return {
            "ok": self.ok,
            "product_type": "guide_worker_local_trajectory_orchestration",
            "scenario": {
                "trajectory_id": self.request.trajectory_id,
                "guide_agent_id": self.request.guide_agent_id,
                "worker_agent_id": self.request.worker_agent_id,
                "runtime_provider": runtime_provider,
                "worker_runtime_providers": list(worker_runtime_providers),
                "parallelism_contract": "one_ready_worker_task_per_lane_per_wave",
                "execution_model": "scheduled_parallel_wave_sequential_fake_runtime",
            },
            "paths": {
                "artifact_store_path": str(self.request.artifact_store_path),
                "admission_ledger_path": str(self.request.admission_ledger_path),
                "snapshot_path": str(self.request.snapshot_path),
                "event_log_path": str(self.request.event_log_path),
            },
            "artifacts": {
                "guide_instruction": f"{self.guide_artifact_id}@{self.guide_artifact_version}",
                "scheduler_batch": f"{self.scheduler_artifact_id}@{self.scheduler_artifact_version}",
            },
            "submitted_task_ids": list(self.submitted_task_ids),
            "lane_ids": list(self.lane_ids),
            "parallel_waves": [wave.to_json_dict() for wave in self.parallel_waves],
            "planning": {
                "planner": self.request.planning_request.planner
                or "deterministic-lane-spec-v1",
                "source": self.planning_source,
                "leader_agent_id": self.request.guide_agent_id,
                "worker_count": len(self.planned_worker_instructions),
                "task_title": self.request.planning_request.task_title,
                "task_summary": self.request.planning_request.task_summary,
                "lane_spec_count": len(self.request.planning_request.lane_specs),
                "generated_instruction_count": len(self.planned_worker_instructions),
            },
            "planned_worker_instructions": [
                _instruction_to_payload(instruction, self.request)
                for instruction in self.planned_worker_instructions
            ],
            "wave_execution_results": [
                result.to_json_dict() for result in self.wave_execution_results
            ],
            "run_task_ids": list(run_task_ids),
            "task_states": task_states,
            "admission_result": dict(self.admission_result),
            "authority_split": {
                "guide_instruction_authority": "exchange_artifact_store",
                "task_lifecycle_authority": "scheduler_snapshot_and_event_log",
                "admission_authority": "exchange_artifact_admission_ledger",
                "parallel_wave_authority": "scheduler_ready_state_by_lane",
                "exchange_store_mutated": True,
                "scheduler_state_mutated": True,
                "admission_ledger_mutated": True,
                "provider_executed": bool(self.run_results),
                "runtime_provider": runtime_provider,
                "worker_runtime_providers": list(worker_runtime_providers),
                "true_process_parallelism": any(
                    result.mode == "threaded" and result.invoked_as_wave
                    for result in self.wave_execution_results
                ),
                "wave_executor_mode": self.request.wave_execution_mode,
                "scheduler_projection_refreshed": False,
                "local_work_trajectory_mutated": False,
                "raw_transcript_persisted": False,
            },
        }


_GUIDE_WORKER_INSTRUCTION_KEY_ALIASES = {
    "taskId": "task_id",
    "laneId": "lane_id",
    "contextId": "context_id",
    "workerAgentId": "worker_agent_id",
    "workerRuntimeProvider": "worker_runtime_provider",
    "allowedArtifacts": "allowed_artifacts",
    "dependsOnTaskIds": "depends_on_task_ids",
    "outputArtifactId": "output_artifact_id",
    "sandboxProfile": "sandbox_profile",
}


def guide_worker_instruction_from_mapping(
    value: dict[str, Any],
    *,
    index: int | None = None,
) -> GuideWorkerInstruction:
    """Build a guide-worker instruction from MCP/JSON-style mapping input."""

    if not isinstance(value, dict):
        path = "workerInstructions"
        if index is not None:
            path = f"{path}[{index}]"
        raise ValueError(f"{path} must be an object")
    normalized = {
        _GUIDE_WORKER_INSTRUCTION_KEY_ALIASES.get(str(key), str(key)): item
        for key, item in value.items()
    }
    prefix = "workerInstructions"
    if index is not None:
        prefix = f"{prefix}[{index}]"

    def require_string(field: str) -> str:
        raw = normalized.get(field, "")
        if not isinstance(raw, str) or not raw.strip():
            raise ValueError(f"{prefix}.{field} must be a non-empty string")
        return raw.strip()

    def optional_string(field: str) -> str:
        raw = normalized.get(field, "")
        if raw in (None, ""):
            return ""
        if not isinstance(raw, str):
            raise ValueError(f"{prefix}.{field} must be a string when provided")
        return raw.strip()

    def string_tuple(field: str) -> tuple[str, ...]:
        raw = normalized.get(field, ())
        if raw in (None, ""):
            return ()
        if not isinstance(raw, (list, tuple)):
            raise ValueError(f"{prefix}.{field} must be a list of strings")
        items: list[str] = []
        for item_index, item in enumerate(raw):
            if not isinstance(item, str) or not item.strip():
                raise ValueError(
                    f"{prefix}.{field}[{item_index}] must be a non-empty string"
                )
            items.append(item.strip())
        return tuple(items)

    sandbox_profile = _sandbox_profile_from_mapping(
        normalized.get("sandbox_profile"),
        path=f"{prefix}.sandbox_profile",
        default_profile_id="shared-process",
    )

    return GuideWorkerInstruction(
        task_id=require_string("task_id"),
        title=require_string("title"),
        instruction=require_string("instruction"),
        lane_id=require_string("lane_id"),
        context_id=optional_string("context_id"),
        worker_agent_id=optional_string("worker_agent_id"),
        worker_runtime_provider=optional_string("worker_runtime_provider"),
        allowed_artifacts=string_tuple("allowed_artifacts"),
        acceptance=string_tuple("acceptance"),
        depends_on_task_ids=string_tuple("depends_on_task_ids"),
        output_artifact_id=optional_string("output_artifact_id"),
        sandbox_profile=sandbox_profile,
    )


def guide_worker_instructions_from_sequence(
    value: object,
) -> tuple[GuideWorkerInstruction, ...]:
    """Build guide-worker instructions from a JSON/MCP list payload."""

    if value in (None, ""):
        return ()
    if not isinstance(value, (list, tuple)):
        raise ValueError("workerInstructions must be a list of instruction objects")
    return tuple(
        guide_worker_instruction_from_mapping(item, index=index)
        for index, item in enumerate(value)
    )


def resolve_guide_worker_instructions(
    request: GuideWorkerLocalOrchestrationRequest,
) -> tuple[tuple[GuideWorkerInstruction, ...], str]:
    """Resolve the concrete worker instructions that a request will execute."""

    return _resolve_worker_instructions(request)


def run_guide_worker_local_trajectory_orchestration(
    request: GuideWorkerLocalOrchestrationRequest,
    *,
    runtime_registry: AgentRuntimeAdapterRegistry | None = None,
    sandbox_registry: SandboxProviderRegistry | None = None,
    artifact_store: InMemoryArtifactVersionStore | None = None,
) -> GuideWorkerLocalOrchestrationResult:
    """Run one deterministic guide/worker orchestration slice."""

    _validate_request(request)

    instructions, planning_source = resolve_guide_worker_instructions(request)
    _validate_instructions(request, instructions)

    version = "v1"
    guide_artifact_id = f"{request.artifact_id_prefix}:guide-instructions"
    scheduler_artifact_id = f"{request.artifact_id_prefix}:worker-batch"

    store = JsonArtifactVersionStore(request.artifact_store_path)
    guide_artifact = _build_guide_instruction_artifact(
        request=request,
        instructions=instructions,
        artifact_id=guide_artifact_id,
        version=version,
    )
    store.put(guide_artifact, replace_existing=request.replace_existing)
    _mirror_artifact_to_memory_store(artifact_store, guide_artifact)

    batch_artifact = _build_scheduler_batch_artifact(
        request=request,
        instructions=instructions,
        guide_artifact_id=guide_artifact_id,
        guide_artifact_version=version,
        artifact_id=scheduler_artifact_id,
        version=version,
    )
    store.put(batch_artifact, replace_existing=request.replace_existing)
    _mirror_artifact_to_memory_store(artifact_store, batch_artifact)

    admission = admit_exchange_artifact_version_with_ledger(
        artifact_store_path=request.artifact_store_path,
        artifact_id=scheduler_artifact_id,
        version=version,
        snapshot_path=request.snapshot_path,
        event_log_path=request.event_log_path,
        admission_ledger_path=request.admission_ledger_path,
        allow_duplicate_admission=request.allow_duplicate_admission,
        replace_existing=request.replace_existing,
        actor=request.guide_agent_id,
        surface="runtime:guide-worker-local-trajectory-orchestration",
        timestamp=request.timestamp,
    )
    if not admission.get("ok"):
        raise ValueError(
            "guide/worker local orchestration scheduler admission failed: "
            f"{admission.get('error', 'unknown error')}"
        )

    state = read_scheduler_state_snapshot(request.snapshot_path)
    event_log = JsonlSchedulerEventLog(request.event_log_path)
    registry = runtime_registry or _default_runtime_registry(artifact_store, request)
    sandboxes = sandbox_registry or _default_sandbox_registry()

    parallel_waves: list[GuideWorkerParallelWave] = []
    wave_execution_results: list[GuideWorkerWaveExecutionResult] = []
    run_results: list[PreflightedTaskRunResult] = []
    current = mark_ready_tasks(state, event_log=event_log, timestamp=request.timestamp)
    for wave_index in range(1, request.max_waves + 1):
        wave = select_ready_worker_parallel_wave(
            current,
            submitted_task_ids=tuple(instruction.task_id for instruction in instructions),
            max_parallel_lanes=request.max_parallel_lanes,
            wave_index=wave_index,
        )
        if not wave.task_ids:
            break
        parallel_waves.append(wave)
        wave_result = execute_guide_worker_parallel_wave(
            current,
            wave,
            runtime_registry=registry,
            sandbox_registry=sandboxes,
            event_log=event_log,
            workspace_root=request.workspace_root,
            scratch_root=request.scratch_root,
            timestamp=request.timestamp,
            mode=request.wave_execution_mode,
        )
        wave_execution_results.append(wave_result)
        run_results.extend(wave_result.run_results)
        current = mark_ready_tasks(
            wave_result.state,
            event_log=event_log,
            timestamp=request.timestamp,
        )
    write_scheduler_state_snapshot(current, request.snapshot_path)

    return GuideWorkerLocalOrchestrationResult(
        request=request,
        guide_artifact_id=guide_artifact_id,
        guide_artifact_version=version,
        scheduler_artifact_id=scheduler_artifact_id,
        scheduler_artifact_version=version,
        submitted_task_ids=tuple(instruction.task_id for instruction in instructions),
        lane_ids=tuple(dict.fromkeys(instruction.lane_id for instruction in instructions)),
        parallel_waves=tuple(parallel_waves),
        planned_worker_instructions=instructions,
        planning_source=planning_source,
        wave_execution_results=tuple(wave_execution_results),
        run_results=tuple(run_results),
        final_state=current,
        admission_result=dict(admission),
    )


def select_ready_worker_parallel_wave(
    state: SchedulerState,
    *,
    submitted_task_ids: tuple[str, ...],
    max_parallel_lanes: int,
    wave_index: int = 1,
) -> GuideWorkerParallelWave:
    """Select at most one ready task per lane from a submitted worker set."""

    if max_parallel_lanes < 1:
        raise ValueError("guide/worker local orchestration requires max_parallel_lanes >= 1")
    selected_task_ids: list[str] = []
    selected_lane_ids: list[str] = []
    seen_lanes: set[str] = set()
    for task_id in sorted(submitted_task_ids):
        task = state.tasks.get(task_id)
        if task is None or task.state != "ready":
            continue
        lane_id = task.context_scope.lane_id or "lane:default"
        if lane_id in seen_lanes:
            continue
        selected_task_ids.append(task_id)
        selected_lane_ids.append(lane_id)
        seen_lanes.add(lane_id)
        if len(selected_task_ids) >= max_parallel_lanes:
            break
    return GuideWorkerParallelWave(
        wave_id=f"parallel-wave:{wave_index:03d}",
        task_ids=tuple(selected_task_ids),
        lane_ids=tuple(selected_lane_ids),
    )


def execute_guide_worker_parallel_wave(
    state: SchedulerState,
    wave: GuideWorkerParallelWave,
    *,
    runtime_registry: AgentRuntimeAdapterRegistry,
    sandbox_registry: SandboxProviderRegistry,
    event_log: SchedulerEventSink | None = None,
    workspace_root: str = "",
    scratch_root: str = DEFAULT_DBC_SCRATCH_ROOT,
    timestamp: str = "",
    mode: GuideWorkerWaveExecutionMode = "serial",
) -> GuideWorkerWaveExecutionResult:
    """Execute one selected guide-worker wave and merge results deterministically."""

    if mode not in ("serial", "threaded"):
        raise ValueError(f"unsupported guide-worker wave execution mode: {mode!r}")
    if not wave.task_ids:
        return GuideWorkerWaveExecutionResult(
            wave=wave,
            mode=mode,
            attempted_task_ids=(),
            completed_task_ids=(),
            failed_task_ids=(),
            deterministic_merge_order=(),
            run_results=(),
            state=state,
        )

    preflights = tuple(
        build_orchestration_preflight_bundle(
            state.tasks[task_id],
            sandbox_registry=sandbox_registry,
            scheduler_state=state,
            workspace_root=workspace_root,
            scratch_root=scratch_root,
            created_at=timestamp,
            expires_at="",
        )
        for task_id in wave.task_ids
    )
    running_state = _mark_wave_tasks_running(
        state,
        preflights,
        event_log=event_log,
        timestamp=timestamp,
    )
    task_runs = _invoke_wave_runtime_tasks(
        preflights,
        runtime_registry=runtime_registry,
        mode=mode,
    )

    current = running_state
    run_results: list[PreflightedTaskRunResult] = []
    completed_task_ids: list[str] = []
    failed_task_ids: list[str] = []
    for task_run in sorted(task_runs, key=lambda item: item.task_id):
        if task_run.runtime_result is None:
            failed_task_ids.append(task_run.task_id)
            current = _merge_wave_task_failure(
                current,
                task_run,
                event_log=event_log,
                timestamp=timestamp,
            )
            continue
        current = _merge_wave_task_success(
            current,
            task_run,
            event_log=event_log,
            timestamp=timestamp,
        )
        completed_task_ids.append(task_run.task_id)
        run_results.append(
            PreflightedTaskRunResult(
                preflight=next(
                    preflight for preflight in preflights
                    if preflight.task.task_id == task_run.task_id
                ),
                state=current,
                runtime_result=task_run.runtime_result,
            )
        )
        current = wake_dependent_tasks(
            current,
            task_run.task_id,
            event_log=event_log,
            timestamp=timestamp,
        )

    return GuideWorkerWaveExecutionResult(
        wave=wave,
        mode=mode,
        attempted_task_ids=tuple(wave.task_ids),
        completed_task_ids=tuple(completed_task_ids),
        failed_task_ids=tuple(failed_task_ids),
        deterministic_merge_order=tuple(sorted(wave.task_ids)),
        run_results=tuple(run_results),
        state=current,
    )


def _build_guide_instruction_artifact(
    *,
    request: GuideWorkerLocalOrchestrationRequest,
    instructions: tuple[GuideWorkerInstruction, ...],
    artifact_id: str,
    version: str,
) -> ExchangeArtifact:
    return ExchangeArtifact(
        artifact_id=artifact_id,
        version=version,
        kind="request",
        intent="ask",
        producer=request.guide_agent_id,
        audience=tuple(
            dict.fromkeys(
                instruction.worker_agent_id or request.worker_agent_id
                for instruction in instructions
            )
        ),
        scope=ExchangeScope(
            trajectory_id=request.trajectory_id,
            lane_id="lane:guide",
            context_id=f"context/{request.artifact_id_prefix}/guide",
            agent_id=request.guide_agent_id,
        ),
        causality=ExchangeCausality(correlation_id=artifact_id),
        lifecycle_state="proposed",
        visibility_policy=VisibilityPolicy(
            audience=(request.guide_agent_id, request.worker_agent_id),
            cross_lane=True,
        ),
        created_at=request.timestamp,
        parts=(
            ExchangePayloadPart(
                part_type="text",
                text="Guide assigns concrete worker tasks for a local trajectory slice.",
            ),
            ExchangePayloadPart(
                part_type="structured",
                data={
                    "product_type": "guide_worker_instruction_set",
                    "trajectory_id": request.trajectory_id,
                    "parallelism_contract": "one_ready_worker_task_per_lane_per_wave",
                    "worker_tasks": [
                        _instruction_to_payload(instruction, request)
                        for instruction in instructions
                    ],
                },
            ),
            ExchangePayloadPart(
                part_type="log",
                log=ExchangeLog(
                    timestamp=request.timestamp,
                    actor=request.guide_agent_id,
                    action="guide_worker_local_orchestration_started",
                    channel="guide-worker-local-orchestration",
                    summary="Guide created structured worker instructions.",
                    related_artifact_ids=(artifact_id,),
                ),
            ),
        ),
    )


def _mark_wave_tasks_running(
    state: SchedulerState,
    preflights: tuple[object, ...],
    *,
    event_log: SchedulerEventSink | None,
    timestamp: str,
) -> SchedulerState:
    tasks = dict(state.tasks)
    for preflight in preflights:
        task = preflight.task
        current = tasks.get(task.task_id)
        if current is None:
            raise ValueError(f"wave task {task.task_id!r} is missing from scheduler state")
        if current != task:
            raise ValueError(
                f"wave preflight bundle for task {task.task_id!r} "
                "does not match current scheduler state"
            )
        if current.state != "ready":
            raise ValueError(f"wave task {task.task_id!r} is not ready: {current.state}")
        tasks[task.task_id] = replace(current, state="running")
        _append_scheduler_event(
            event_log,
            event_kind="task_running",
            task_id=task.task_id,
            from_state="ready",
            to_state="running",
            timestamp=timestamp,
        )
    return replace(state, tasks=tasks)


def _invoke_wave_runtime_tasks(
    preflights: tuple[object, ...],
    *,
    runtime_registry: AgentRuntimeAdapterRegistry,
    mode: GuideWorkerWaveExecutionMode,
) -> tuple[GuideWorkerWaveTaskRun, ...]:
    if mode == "threaded" and len(preflights) > 1:
        with ThreadPoolExecutor(max_workers=len(preflights)) as executor:
            return tuple(
                executor.map(
                    lambda preflight: _invoke_wave_runtime_task(
                        preflight,
                        runtime_registry=runtime_registry,
                    ),
                    preflights,
                )
            )
    return tuple(
        _invoke_wave_runtime_task(preflight, runtime_registry=runtime_registry)
        for preflight in preflights
    )


def _invoke_wave_runtime_task(
    preflight: object,
    *,
    runtime_registry: AgentRuntimeAdapterRegistry,
) -> GuideWorkerWaveTaskRun:
    task = preflight.task
    try:
        runtime = runtime_registry.get(task.agent.runtime_provider)
        session = runtime.start_session(task.agent)
        result = runtime.run_task(session, preflight.runtime_task)
        return GuideWorkerWaveTaskRun(
            task_id=task.task_id,
            lane_id=task.context_scope.lane_id,
            runtime_result=result,
        )
    except Exception as exc:
        return GuideWorkerWaveTaskRun(
            task_id=task.task_id,
            lane_id=task.context_scope.lane_id,
            error=str(exc) or type(exc).__name__,
        )


def _merge_wave_task_success(
    state: SchedulerState,
    task_run: GuideWorkerWaveTaskRun,
    *,
    event_log: SchedulerEventSink | None,
    timestamp: str,
) -> SchedulerState:
    result = task_run.runtime_result
    if result is None:
        raise ValueError(f"cannot merge missing runtime result for task {task_run.task_id!r}")
    running = state.tasks[task_run.task_id]
    output_ref = ExchangeReference(
        ref_kind="exchange_artifact",
        ref_id=result.output_artifact.artifact_id,
        version=result.output_artifact.version,
    )
    next_state = "review_required" if result.permission_requests else "complete"
    blocked_reason = _permission_review_reason(result.permission_requests)
    completed = replace(
        running,
        state=next_state,
        blocked_reason=blocked_reason,
        run_id=result.run_handle.run_id,
        output_artifact_ref=output_ref,
    )
    tasks = dict(state.tasks)
    tasks[task_run.task_id] = completed
    run_record = TaskRunRecord(
        task_id=task_run.task_id,
        run_id=result.run_handle.run_id,
        session_id=result.run_handle.session_id,
        output_artifact_id=result.output_artifact.artifact_id,
        output_artifact_version=result.output_artifact.version,
        state=next_state,
    )
    updated = replace(state, tasks=tasks, run_records=state.run_records + (run_record,))
    _append_scheduler_event(
        event_log,
        event_kind="task_review_required" if result.permission_requests else "task_completed",
        task_id=task_run.task_id,
        from_state="running",
        to_state=next_state,
        reason=blocked_reason,
        run_id=result.run_handle.run_id,
        session_id=result.run_handle.session_id,
        output_artifact_id=result.output_artifact.artifact_id,
        output_artifact_version=result.output_artifact.version,
        related_artifact_ids=(result.output_artifact.artifact_id,),
        timestamp=timestamp,
    )
    return updated


def _merge_wave_task_failure(
    state: SchedulerState,
    task_run: GuideWorkerWaveTaskRun,
    *,
    event_log: SchedulerEventSink | None,
    timestamp: str,
) -> SchedulerState:
    reason = _runtime_failure_reason(task_run.error)
    failed = replace(
        state.tasks[task_run.task_id],
        state="blocked",
        blocked_reason=reason,
    )
    tasks = dict(state.tasks)
    tasks[task_run.task_id] = failed
    updated = replace(state, tasks=tasks)
    _append_scheduler_event(
        event_log,
        event_kind="task_run_failed",
        task_id=task_run.task_id,
        from_state="running",
        to_state="blocked",
        reason=reason,
        timestamp=timestamp,
    )
    return updated


def _append_scheduler_event(
    event_log: SchedulerEventSink | None,
    *,
    event_kind: str,
    task_id: str,
    from_state: str,
    to_state: str,
    timestamp: str,
    reason: str = "",
    run_id: str = "",
    session_id: str = "",
    output_artifact_id: str = "",
    output_artifact_version: str = "",
    related_artifact_ids: tuple[str, ...] = (),
) -> None:
    if event_log is None:
        return
    sequence = len(event_log.read_all()) + 1
    event_log.append(
        SchedulerEvent(
            event_id=f"scheduler-event-{sequence}",
            event_kind=event_kind,
            timestamp=timestamp,
            task_id=task_id,
            from_state=from_state,
            to_state=to_state,
            reason=reason,
            run_id=run_id,
            session_id=session_id,
            output_artifact_id=output_artifact_id,
            output_artifact_version=output_artifact_version,
            related_artifact_ids=related_artifact_ids,
            sequence=sequence,
        )
    )


def _permission_review_reason(permission_requests: tuple[object, ...]) -> str:
    if not permission_requests:
        return ""
    if len(permission_requests) == 1:
        request = permission_requests[0]
        return f"permission review required: {request.request_kind} {request.target}".rstrip()
    return f"permission review required: {len(permission_requests)} requests"


def _runtime_failure_reason(reason: str) -> str:
    prefix = "runtime failure: "
    return reason if reason.startswith(prefix) else f"{prefix}{reason}"


def _build_scheduler_batch_artifact(
    *,
    request: GuideWorkerLocalOrchestrationRequest,
    instructions: tuple[GuideWorkerInstruction, ...],
    guide_artifact_id: str,
    guide_artifact_version: str,
    artifact_id: str,
    version: str,
) -> ExchangeArtifact:
    submissions = tuple(
        _instruction_to_submission(
            request,
            instruction,
            guide_artifact_id=guide_artifact_id,
            guide_artifact_version=guide_artifact_version,
        )
        for instruction in instructions
    )
    batch = SchedulerTaskBatchSubmission(
        batch_id=f"batch/{request.artifact_id_prefix}",
        title="Guide-assigned worker batch",
        summary="Worker tasks generated by guide for one Local Work Trajectory slice.",
        tasks=submissions,
    )
    artifact = scheduler_task_batch_submission_to_artifact(
        batch,
        artifact_id=artifact_id,
        producer=request.guide_agent_id,
        created_at=request.timestamp,
        version=version,
    )
    return replace(
        artifact,
        audience=tuple(
            dict.fromkeys(
                (request.guide_agent_id,)
                + tuple(
                    instruction.worker_agent_id or request.worker_agent_id
                    for instruction in instructions
                )
            )
        ),
        scope=ExchangeScope(
            trajectory_id=request.trajectory_id,
            lane_id="lane:guide",
            context_id=f"context/{request.artifact_id_prefix}/guide",
            agent_id=request.guide_agent_id,
        ),
        causality=ExchangeCausality(
            caused_by=(f"{guide_artifact_id}@{guide_artifact_version}",),
            correlation_id=guide_artifact_id,
        ),
        visibility_policy=VisibilityPolicy(
            audience=tuple(
                dict.fromkeys(
                    (request.guide_agent_id,)
                    + tuple(
                        instruction.worker_agent_id or request.worker_agent_id
                        for instruction in instructions
                    )
                )
            ),
            cross_lane=True,
        ),
    )


def _instruction_to_submission(
    request: GuideWorkerLocalOrchestrationRequest,
    instruction: GuideWorkerInstruction,
    *,
    guide_artifact_id: str,
    guide_artifact_version: str,
) -> SchedulerTaskSubmission:
    worker_agent_id = instruction.worker_agent_id or request.worker_agent_id
    runtime_provider = instruction.worker_runtime_provider or "fake"
    return SchedulerTaskSubmission(
        task_id=instruction.task_id,
        title=instruction.title,
        instruction=instruction.instruction,
        agent=AgentSpec(
            agent_id=worker_agent_id,
            runtime_provider=runtime_provider,  # type: ignore[arg-type]
            display_name=f"Worker for {instruction.lane_id}",
        ),
        context_scope=ContextScope(
            context_id=(
                instruction.context_id
                or f"context/{request.artifact_id_prefix}/{instruction.lane_id}"
            ),
            lane_id=instruction.lane_id,
            required_refs=(
                ExchangeReference(
                    ref_kind="exchange_artifact",
                    ref_id=guide_artifact_id,
                    version=guide_artifact_version,
                ),
            ),
            visible_artifacts=(guide_artifact_id,),
        ),
        edit_lease=_edit_lease_for_instruction(instruction),
        sandbox_profile=SandboxProfile(
            profile_id=(
                f"sandbox/{instruction.task_id}"
                if instruction.sandbox_profile.profile_id == "shared-process"
                else instruction.sandbox_profile.profile_id
            ),
            profile_kind=instruction.sandbox_profile.profile_kind,
            network_policy=instruction.sandbox_profile.network_policy,
            secret_policy=instruction.sandbox_profile.secret_policy,
            mount_policy=instruction.sandbox_profile.mount_policy,
        ),
        input_artifact_refs=(
            ExchangeReference(
                ref_kind="exchange_artifact",
                ref_id=guide_artifact_id,
                version=guide_artifact_version,
            ),
        ),
        acceptance=instruction.acceptance or (
            "Worker result artifact records the completed task.",
            "No agent-owned Local Work Trajectory mutation is performed by runtime code.",
        ),
        output_artifact_id=instruction.output_artifact_id or f"{instruction.task_id}:result",
        dependencies=tuple(
            TaskDependency(
                dependency_id=f"dep/{source_task_id}->{instruction.task_id}",
                source_task_id=source_task_id,
                target_task_id=instruction.task_id,
                dependency_kind="depends_on",
                required_state="complete",
            )
            for source_task_id in instruction.depends_on_task_ids
        ),
    )


def _edit_lease_for_instruction(instruction: GuideWorkerInstruction) -> EditScopeLease | None:
    if not instruction.allowed_artifacts:
        return None
    return EditScopeLease(
        lease_id=f"lease/{instruction.task_id}",
        task_id=instruction.task_id,
        allowed_artifacts=instruction.allowed_artifacts,
        lease_mode="write",
        conflict_policy="block-on-overlap",
    )


def _instruction_to_payload(
    instruction: GuideWorkerInstruction,
    request: GuideWorkerLocalOrchestrationRequest,
) -> dict[str, object]:
    return {
        "task_id": instruction.task_id,
        "title": instruction.title,
        "instruction": instruction.instruction,
        "lane_id": instruction.lane_id,
        "context_id": (
            instruction.context_id
            or f"context/{request.artifact_id_prefix}/{instruction.lane_id}"
        ),
        "worker_agent_id": instruction.worker_agent_id or request.worker_agent_id,
        "worker_runtime_provider": instruction.worker_runtime_provider or "fake",
        "allowed_artifacts": list(instruction.allowed_artifacts),
        "acceptance": list(instruction.acceptance),
        "depends_on_task_ids": list(instruction.depends_on_task_ids),
        "output_artifact_id": instruction.output_artifact_id or f"{instruction.task_id}:result",
        "sandbox_profile": _sandbox_profile_to_payload(instruction.sandbox_profile),
    }


def _sandbox_profile_to_payload(profile: SandboxProfile) -> dict[str, object]:
    return {
        "profile_id": profile.profile_id,
        "profile_kind": profile.profile_kind,
        "network_policy": profile.network_policy,
        "secret_policy": profile.secret_policy,
        "mount_policy": profile.mount_policy,
    }


def _sandbox_profile_from_mapping(
    value: object,
    *,
    path: str,
    default_profile_id: str,
) -> SandboxProfile:
    if value in (None, ""):
        return SandboxProfile(
            profile_id=default_profile_id,
            profile_kind="shared-process",
            network_policy="disabled",
            secret_policy="deny",
            mount_policy="lease-scoped",
        )
    if not isinstance(value, dict):
        raise ValueError(f"{path} must be an object when provided")
    normalized = {
        {
            "profileId": "profile_id",
            "profileKind": "profile_kind",
            "networkPolicy": "network_policy",
            "secretPolicy": "secret_policy",
            "mountPolicy": "mount_policy",
        }.get(str(key), str(key)): item
        for key, item in value.items()
    }
    profile_kind = str(normalized.get("profile_kind", "shared-process") or "shared-process")
    if profile_kind not in {"none", "shared-process", "git-worktree", "docker", "remote-vm"}:
        raise ValueError(
            f"{path}.profile_kind must be one of none, shared-process, "
            f"git-worktree, docker, or remote-vm; got {profile_kind!r}"
        )
    return SandboxProfile(
        profile_id=str(normalized.get("profile_id", "") or default_profile_id),
        profile_kind=profile_kind,  # type: ignore[arg-type]
        network_policy=str(normalized.get("network_policy", "disabled") or "disabled"),
        secret_policy=str(normalized.get("secret_policy", "deny") or "deny"),
        mount_policy=str(normalized.get("mount_policy", "lease-scoped") or "lease-scoped"),
    )


def _default_worker_instructions(
    request: GuideWorkerLocalOrchestrationRequest,
) -> tuple[GuideWorkerInstruction, ...]:
    prefix = request.artifact_id_prefix
    return (
        GuideWorkerInstruction(
            task_id=f"task/{prefix}/client",
            title="Implement client slice",
            instruction=(
                "Work only on the client-facing slice. Produce a deterministic "
                "result artifact describing the intended client change."
            ),
            lane_id="lane:client",
            allowed_artifacts=("client",),
            acceptance=(
                "Client slice has a concrete result artifact.",
                "No server files are in the worker edit lease.",
            ),
        ),
        GuideWorkerInstruction(
            task_id=f"task/{prefix}/server",
            title="Implement server slice",
            instruction=(
                "Work only on the server-facing slice. Produce a deterministic "
                "result artifact describing the intended server change."
            ),
            lane_id="lane:server",
            allowed_artifacts=("server",),
            acceptance=(
                "Server slice has a concrete result artifact.",
                "No client files are in the worker edit lease.",
            ),
        ),
    )


def _resolve_worker_instructions(
    request: GuideWorkerLocalOrchestrationRequest,
) -> tuple[tuple[GuideWorkerInstruction, ...], str]:
    if request.worker_instructions:
        return request.worker_instructions, "explicit_worker_instructions"
    if request.planning_request.lane_specs:
        return _planned_worker_instructions(request), "planning_request"
    return _default_worker_instructions(request), "default_planner"


def _planned_worker_instructions(
    request: GuideWorkerLocalOrchestrationRequest,
) -> tuple[GuideWorkerInstruction, ...]:
    planning = request.planning_request
    task_title = planning.task_title.strip() or "Local trajectory work"
    task_summary = planning.task_summary.strip() or task_title
    lane_ids = {spec.lane_id for spec in planning.lane_specs}
    instructions: list[GuideWorkerInstruction] = []
    for spec in planning.lane_specs:
        lane_id = spec.lane_id.strip()
        label = spec.label.strip() or lane_id.replace("lane:", "").replace("-", " ").title()
        focus = spec.focus.strip() or label
        if not lane_id:
            raise ValueError("planning_request.lane_specs requires non-empty lane_id")
        unknown_dependencies = [
            dependency
            for dependency in spec.depends_on_lane_ids
            if dependency not in lane_ids
        ]
        if unknown_dependencies:
            raise ValueError(
                "planning_request.lane_specs dependency lane id not found: "
                f"{', '.join(unknown_dependencies)}"
            )
        task_suffix = _safe_task_suffix(lane_id)
        task_id = f"task/{request.artifact_id_prefix}/{task_suffix}"
        depends_on_task_ids = tuple(
            f"task/{request.artifact_id_prefix}/{_safe_task_suffix(dependency)}"
            for dependency in spec.depends_on_lane_ids
        )
        instructions.append(
            GuideWorkerInstruction(
                task_id=task_id,
                title=label,
                instruction=(
                    f"Work on the '{label}' lane for: {task_title}. "
                    f"Lane focus: {focus}. Overall task context: {task_summary}. "
                    "Produce a deterministic worker result artifact summarizing "
                    "the completed work, changed surface, and validation evidence."
                ),
                lane_id=lane_id,
                worker_agent_id=spec.worker_agent_id,
                worker_runtime_provider=spec.worker_runtime_provider,
                allowed_artifacts=spec.allowed_artifacts,
                acceptance=spec.acceptance
                or (
                    f"{label} lane result artifact exists.",
                    "Result records concrete validation evidence or a clear blocker.",
                ),
                depends_on_task_ids=depends_on_task_ids,
                output_artifact_id=f"{task_id}:result",
                sandbox_profile=spec.sandbox_profile,
            )
        )
    return tuple(instructions)


def _safe_task_suffix(value: str) -> str:
    suffix = value.strip().lower()
    if suffix.startswith("lane:"):
        suffix = suffix[len("lane:") :]
    suffix = "".join(ch if ch.isalnum() else "-" for ch in suffix).strip("-")
    return suffix or "work"


def _default_runtime_registry(
    artifact_store: InMemoryArtifactVersionStore | None,
    request: GuideWorkerLocalOrchestrationRequest,
) -> AgentRuntimeAdapterRegistry:
    registry = AgentRuntimeAdapterRegistry()
    registry.register(
        FakeAgentRuntimeAdapter(
            artifact_store=artifact_store
            or _in_memory_store_from_json(request.artifact_store_path),
            event_log=None,
            timestamp=request.timestamp,
        )
    )
    return registry


def _in_memory_store_from_json(path: Path) -> InMemoryArtifactVersionStore:
    memory = InMemoryArtifactVersionStore()
    if not path.exists():
        return memory
    for record in JsonArtifactVersionStore(path).list_records():
        try:
            memory.put(record.artifact)
        except ValueError as exc:
            if "already exists" not in str(exc):
                raise
    return memory


def _mirror_artifact_to_memory_store(
    artifact_store: InMemoryArtifactVersionStore | None,
    artifact: ExchangeArtifact,
) -> None:
    if artifact_store is None:
        return
    try:
        artifact_store.put(artifact)
    except ValueError as exc:
        if "already exists" not in str(exc):
            raise


def _default_sandbox_registry() -> SandboxProviderRegistry:
    registry = SandboxProviderRegistry()
    registry.register(SharedProcessSandboxProvider())
    return registry


def _validate_request(request: GuideWorkerLocalOrchestrationRequest) -> None:
    if not request.artifact_store_path:
        raise ValueError("guide/worker local orchestration requires artifact_store_path")
    if not request.admission_ledger_path:
        raise ValueError("guide/worker local orchestration requires admission_ledger_path")
    if not request.snapshot_path:
        raise ValueError("guide/worker local orchestration requires snapshot_path")
    if not request.event_log_path:
        raise ValueError("guide/worker local orchestration requires event_log_path")
    if not request.trajectory_id:
        raise ValueError("guide/worker local orchestration requires trajectory_id")
    if not request.guide_agent_id:
        raise ValueError("guide/worker local orchestration requires guide_agent_id")
    if not request.worker_agent_id:
        raise ValueError("guide/worker local orchestration requires worker_agent_id")
    if request.guide_agent_id == request.worker_agent_id:
        raise ValueError("guide/worker local orchestration requires distinct guide and worker agents")
    if not request.artifact_id_prefix:
        raise ValueError("guide/worker local orchestration requires artifact_id_prefix")
    if request.max_parallel_lanes < 1:
        raise ValueError("guide/worker local orchestration requires max_parallel_lanes >= 1")
    if request.max_waves < 1:
        raise ValueError("guide/worker local orchestration requires max_waves >= 1")


def _validate_instructions(
    request: GuideWorkerLocalOrchestrationRequest,
    instructions: tuple[GuideWorkerInstruction, ...],
) -> None:
    if not instructions:
        raise ValueError("guide/worker local orchestration requires at least one worker instruction")
    seen_task_ids: set[str] = set()
    for index, instruction in enumerate(instructions):
        prefix = f"worker_instructions[{index}]"
        if not instruction.task_id:
            raise ValueError(f"{prefix} requires task_id")
        if instruction.task_id in seen_task_ids:
            raise ValueError(f"duplicate worker task_id: {instruction.task_id!r}")
        seen_task_ids.add(instruction.task_id)
        if not instruction.title:
            raise ValueError(f"{prefix} requires title")
        if not instruction.instruction:
            raise ValueError(f"{prefix} requires instruction")
        if not instruction.lane_id:
            raise ValueError(f"{prefix} requires lane_id")
        for source_task_id in instruction.depends_on_task_ids:
            if source_task_id not in seen_task_ids:
                known = ", ".join(sorted(seen_task_ids)) or "(none)"
                raise ValueError(
                    f"{prefix} dependency {source_task_id!r} must refer to an earlier "
                    f"instruction task_id; known earlier tasks: {known}"
                )
        worker_agent_id = instruction.worker_agent_id or request.worker_agent_id
        if worker_agent_id == request.guide_agent_id:
            raise ValueError(f"{prefix} worker_agent_id must differ from guide_agent_id")
        runtime_provider = instruction.worker_runtime_provider or "fake"
        if runtime_provider not in {"fake", "qoder", "codex", "opencode"}:
            raise ValueError(
                f"{prefix} worker_runtime_provider must be 'fake', 'qoder', 'codex', "
                f"or 'opencode'; "
                f"got {runtime_provider!r}"
            )
