import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const sourcePath = join(__dirname, '..', '..', 'src', 'webviews', 'localWorkTrajectory.tsx');
const stylePath = join(__dirname, '..', '..', 'src', 'webviews', 'localWorkTrajectory.css');

test('local work trajectory renderer uses lane-first layout instead of wrapping long lines', () => {
  const source = readFileSync(sourcePath, 'utf-8');

  assert.match(source, /const laneStrideY = 142;/);
  assert.match(source, /const eventStrideX = nodeWidth \+ 70;/);
  assert.match(source, /Mode', 'React Flow lanes'/);
  assert.match(source, /function buildLaneNode\(/);
  assert.match(source, /function buildEventNode\(/);
  assert.match(source, /const orderedLanes = orderLanes\(lanes, events, relations\);/);
  assert.doesNotMatch(source, /lanes\.slice\(\)\.sort\(\(left, right\) => left\.id\.localeCompare\(right\.id\)\)/);
  assert.match(source, /function orderLanes\(/);
  assert.match(source, /laneOpeningRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /childLaneIds\.add\(opening\.childLaneId\)/);
  assert.match(source, /childrenByParent\.get\(laneId\) \?\? \[\]/);
  assert.match(source, /function compareLaneRoots\(left: TrajectoryLane, right: TrajectoryLane\): number/);
  assert.match(source, /left\.id === 'lane:main' \? 0 : 1/);
  assert.match(source, /function computeEventColumns\(/);
  assert.match(source, /function computeLaneStartColumns\(/);
  assert.match(source, /function raiseColumnAtLeast\(/);
  assert.match(source, /const maxColumnConstraintPasses = 80;/);
  assert.match(source, /function buildLaneLayout\(/);
  assert.match(source, /setLayout\(buildFallbackLayout\(/);
  assert.match(source, /function buildFallbackLayout\(/);
  assert.match(source, /const isEmptyLifecycle = Boolean\(/);
  assert.match(source, /metadata\?\.lifecycle_state === 'empty'/);
  assert.match(source, /The agent will create the first lane and active event when it starts a tracked task\./);
  assert.match(source, /activeEventId: string \| null;/);
  assert.match(source, /focusEventId: string \| null;/);
  assert.match(source, /type RelationBadge = \{/);
  assert.match(source, /function findActiveEventId\(/);
  assert.match(source, /function findFocusEventId\(/);
  assert.match(source, /'blocked', 'waiting', 'pending', 'completed', 'archived'/);
  assert.match(source, /event\.status === 'in_progress'/);
  assert.match(source, /isActive \? 'pg-lwt-node-active' : ''/);
  assert.match(source, /pg-lwt-node-status-\$\{normalizedStatus\}/);
  assert.match(source, /data-pg-event-active=\{isActive \? 'true' : 'false'\}/);
  assert.match(source, /data-pg-lane-status=\{lane\.status\}/);
  assert.match(source, /function laneBackground\(/);
  assert.match(source, /function eventBackground\(/);
  assert.match(source, /setViewport\(buildFocusedViewport\(activeNode\), \{ duration: 180 \}\);/);
  assert.match(source, /function buildFocusedViewport\(/);
  assert.match(source, /x: \(-activeNode\.position\.x \* zoom\) \+ 300/);
  assert.match(source, /node\.id === layout\.activeEventId/);
  assert.doesNotMatch(source, /buildWrappedLayout/);
  assert.doesNotMatch(source, /readableWrapThreshold/);
  assert.doesNotMatch(source, /wrappedColumns/);
  assert.match(source, /data-pg-lwt-layout-mode=\{layout\.mode\}/);
  assert.match(source, /const alignmentRelationKinds = new Set\(\[/);
  const alignmentSetSource = source.match(/const alignmentRelationKinds = new Set\(\[[\s\S]*?\]\);/)?.[0] ?? '';
  assert.match(alignmentSetSource, /'proposes_new_line'/);
  assert.match(alignmentSetSource, /'approves_new_line'/);
  assert.match(alignmentSetSource, /'merges_into'/);
  assert.doesNotMatch(alignmentSetSource, /'depends_on'/);
  assert.doesNotMatch(alignmentSetSource, /'waits_for'/);
  assert.doesNotMatch(alignmentSetSource, /'syncs_from'/);
  assert.match(source, /alignmentRelationKinds\.has\(relation\.kind\)[\s\S]*raiseColumnAtLeast\(columns, target\.id, sourceColumn \+ 1\)/);
  assert.match(source, /'merges_into'/);
  assert.match(source, /raiseColumnAtLeast\(columns, source\.id, targetColumn - 1\)/);
  assert.match(source, /const laneOpeningRelationKinds = new Set\(\[/);
  assert.match(source, /laneOpeningRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /laneStartColumns\.set\(target\.laneId, eventColumns\.get\(source\.id\) \?\? 0\)/);
  assert.match(source, /x: laneXForColumn\(startColumn\)/);
  assert.match(source, /x: eventXForColumn\(eventColumn\)/);
  assert.match(source, /const auxiliaryRelationKinds = new Set\(\[/);
  assert.match(source, /const relianceRelationKinds = new Set\(\[/);
  const relianceSetSource = source.match(/const relianceRelationKinds = new Set\(\[[\s\S]*?\]\);/)?.[0] ?? '';
  assert.match(relianceSetSource, /'depends_on'/);
  assert.match(relianceSetSource, /'waits_for'/);
  assert.match(relianceSetSource, /'syncs_from'/);
  assert.doesNotMatch(relianceSetSource, /'unblocks'/);
  assert.doesNotMatch(relianceSetSource, /'hands_off'/);
  assert.doesNotMatch(relianceSetSource, /'merges_into'/);
  assert.doesNotMatch(relianceSetSource, /'proposes_new_line'/);
  assert.doesNotMatch(relianceSetSource, /'approves_new_line'/);
  assert.doesNotMatch(source, /const sidePortRelationKinds = new Set\(\[/);
  assert.match(source, /Handle,/);
  assert.match(source, /const relianceTopSourceHandle = 'reliance-top-source';/);
  assert.match(source, /const relianceTopTargetHandle = 'reliance-top-target';/);
  assert.match(source, /const relianceBottomSourceHandle = 'reliance-bottom-source';/);
  assert.match(source, /const relianceBottomTargetHandle = 'reliance-bottom-target';/);
  assert.match(source, /const mainFlowSourceHandle = 'main-flow-source';/);
  assert.match(source, /const mainFlowTargetHandle = 'main-flow-target';/);
  assert.doesNotMatch(source, /const auxiliaryTopSourceHandle = 'aux-top-source';/);
  assert.doesNotMatch(source, /const auxiliaryTopTargetHandle = 'aux-top-target';/);
  assert.doesNotMatch(source, /const auxiliaryBottomSourceHandle = 'aux-bottom-source';/);
  assert.doesNotMatch(source, /const auxiliaryBottomTargetHandle = 'aux-bottom-target';/);
  assert.doesNotMatch(source, /function AuxiliaryRelationHandles\(\): React\.ReactElement/);
  assert.doesNotMatch(source, /function LaneRelationHandles\(\): React\.ReactElement/);
  assert.doesNotMatch(source, /<LaneRelationHandles \/>/);
  assert.doesNotMatch(source, /<AuxiliaryRelationHandles \/>/);
  assert.match(source, /function MainFlowHandles\(\): React\.ReactElement/);
  assert.match(source, /<MainFlowHandles \/>/);
  assert.match(source, /function RelianceOverlayHandles\(\): React\.ReactElement/);
  assert.match(source, /<RelianceOverlayHandles \/>/);
  assert.match(source, /function buildRelationBadgesByEventId\(/);
  assert.match(source, /const relationBadgesByEventId = buildRelationBadgesByEventId\(relations, eventById\);/);
  assert.match(source, /!auxiliaryRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /relationBadgesByEventId\.get\(event\.id\) \?\? \[\]/);
  assert.match(source, /className="pg-lwt-relation-badges"/);
  assert.match(source, /className="pg-lwt-relation-badge"/);
  assert.doesNotMatch(source, /id=\{auxiliaryTopSourceHandle\}[\s\S]*position=\{Position\.Top\}/);
  assert.doesNotMatch(source, /id=\{auxiliaryBottomTargetHandle\}[\s\S]*position=\{Position\.Bottom\}/);
  assert.doesNotMatch(source, /className="pg-lwt-aux-handle"/);
  assert.match(source, /id=\{relianceTopSourceHandle\}[\s\S]*position=\{Position\.Top\}/);
  assert.match(source, /id=\{relianceBottomTargetHandle\}[\s\S]*position=\{Position\.Bottom\}/);
  assert.match(source, /id=\{mainFlowSourceHandle\}[\s\S]*position=\{Position\.Right\}/);
  assert.match(source, /id=\{mainFlowTargetHandle\}[\s\S]*position=\{Position\.Left\}/);
  assert.match(source, /className="pg-lwt-main-flow-handle"/);
  assert.match(source, /className="pg-lwt-reliance-handle"/);
  assert.doesNotMatch(source, /sourcePosition: Position\.Right/);
  assert.doesNotMatch(source, /targetPosition: Position\.Left/);
  assert.match(source, /function buildEventLaneIndexById\(/);
  assert.match(source, /const eventLaneIndexById = buildEventLaneIndexById\(orderedLanes, eventsByLane\);/);
  assert.match(source, /function buildRelationEdge\(relation: TrajectoryRelation\): Edge/);
  assert.match(source, /\.map\(\(relation\) => buildRelationEdge\(relation\)\)/);
  const relationEdgeFunctionSource = source.slice(
    source.indexOf('function buildRelationEdge'),
    source.indexOf('function buildRelianceOverlayEdge'),
  );
  assert.doesNotMatch(source, /const visualDirection = visualRelationDirection\(relation\);/);
  assert.match(relationEdgeFunctionSource, /source: relation\.sourceEventId/);
  assert.match(relationEdgeFunctionSource, /target: relation\.targetEventId/);
  assert.match(source, /sourceHandle: mainFlowSourceHandle/);
  assert.match(source, /targetHandle: mainFlowTargetHandle/);
  assert.doesNotMatch(source, /function sidePortRelationHandles\(/);
  assert.match(source, /type: 'smoothstep'/);
  assert.match(source, /markerEnd: \{/);
  assert.doesNotMatch(source, /function visualRelationDirection\(relation: TrajectoryRelation\)/);
  assert.doesNotMatch(source, /laneOpeningRelationKinds\.has\(relation\.kind\)[\s\S]*target: target\.laneId/);
  assert.doesNotMatch(source, /source: relation\.targetEventId[\s\S]*target: relation\.sourceEventId/);
  assert.match(source, /const relianceEdges = relations[\s\S]*relianceRelationKinds\.has\(relation\.kind\)[\s\S]*buildRelianceOverlayEdge\(relation, eventLaneIndexById\)/);
  assert.match(source, /return \{ nodes, edges: \[\.\.\.sequenceEdges, \.\.\.relationEdges, \.\.\.relianceEdges\], activeEventId, focusEventId \};/);
  assert.match(source, /function buildRelianceOverlayEdge\(/);
  assert.match(source, /sourceHandle: handles\.sourceHandle/);
  assert.match(source, /targetHandle: handles\.targetHandle/);
  assert.match(source, /'pg-lwt-edge-reliance-overlay'/);
  assert.match(source, /function relianceOverlayHandles\(/);
  assert.match(source, /sourceHandle: relianceBottomSourceHandle[\s\S]*targetHandle: relianceTopTargetHandle/);
  assert.match(source, /sourceHandle: relianceTopSourceHandle[\s\S]*targetHandle: relianceBottomTargetHandle/);
  assert.match(source, /const relationStyle = edgeStyleForKind\(kind\);/);
  assert.match(source, /label: isSequence \? undefined : relationStyle\.label/);
  assert.match(source, /function edgeStyleForKind\(kind: string\)/);
  assert.match(source, /case 'depends_on':[\s\S]*label: 'depends'/);
  assert.match(source, /case 'waits_for':[\s\S]*label: 'waits'/);
  assert.match(source, /case 'unblocks':[\s\S]*label: 'unblocks'/);
  assert.match(source, /case 'hands_off':[\s\S]*label: 'handoff'/);
  assert.match(source, /case 'syncs_from':[\s\S]*label: 'sync'/);
  assert.match(source, /case 'approves_new_line':[\s\S]*label: 'approved'/);
  assert.match(source, /className: `pg-lwt-edge-\$\{normalizeStatus\(kind\)\}`/);
  assert.match(source, /strokeDasharray: isSequence \? undefined : relationStyle\.strokeDasharray/);
});

test('local work trajectory stylesheet gives React Flow a stable drawing area', () => {
  const style = readFileSync(stylePath, 'utf-8');

  assert.match(style, /\.pg-lwt-shell \{[\s\S]*height: clamp\(560px, 72vh, 900px\);/);
  assert.match(style, /\.pg-lwt-flow \{[\s\S]*height: 100%;/);
  assert.match(style, /\.pg-lwt-flow \.react-flow \{[\s\S]*height: 100%;/);
  assert.match(style, /linear-gradient\(90deg, rgba\(49, 95, 126, 0\.08\) 0 170px/);
  assert.match(style, /\.pg-lwt-layout-note/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-active/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-active="true"\] strong/);
  assert.match(style, /\.pg-lwt-relation-badges/);
  assert.match(style, /\.pg-lwt-relation-badge/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-status="waiting"\]/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-status="archived"\]/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-status-archived/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.pg-lwt-aux-handle/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__handle:not\(\.pg-lwt-main-flow-handle\):not\(\.pg-lwt-reliance-handle\) \{[\s\S]*opacity: 0;/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-main-flow-handle,/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-reliance-handle \{[\s\S]*opacity: 0;/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-reliance-handle \{[\s\S]*pointer-events: none;/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-merges-into/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-merges-into \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-proposes-new-line/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-proposes-new-line \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-waits-for \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-syncs-from \.react-flow__edge-text/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-auxiliary/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-side-port/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-auxiliary \.react-flow__edge-path/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-unblocks/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-hands-off/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-approves-new-line/);
});
