import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const sourcePath = join(__dirname, '..', '..', 'src', 'webviews', 'localWorkTrajectory.tsx');
const stylePath = join(__dirname, '..', '..', 'src', 'webviews', 'localWorkTrajectory.css');

test('local work trajectory renderer uses lane-first layout instead of wrapping long lines', () => {
  const source = readFileSync(sourcePath, 'utf-8');

  assert.match(source, /const laneStrideY = 188;/);
  assert.match(source, /const dependencyProxyOffset = 38;/);
  assert.match(source, /const dependencyProxyGap = 14;/);
  assert.match(source, /const eventStrideX = nodeWidth \+ 70;/);
  assert.match(source, /const fullFitTargetWidth = 540;/);
  assert.match(source, /const fullFitTargetHeight = 430;/);
  assert.match(source, /Mode', 'React Flow lanes'/);
  assert.match(source, /function buildLaneNode\(/);
  assert.match(source, /function buildEventNode\(/);
  assert.match(source, /type TrajectoryVisualLayerKind = 'node' \| 'edge';/);
  assert.match(source, /type TrajectoryNodeVisualLayerId =/);
  assert.match(source, /type TrajectoryEdgeVisualLayerId =/);
  assert.match(source, /type TrajectoryVisualLayerRegistration/);
  assert.match(source, /function createTrajectoryVisualLayerRegistry\(/);
  assert.match(source, /function registerTrajectoryVisualLayer/);
  assert.match(source, /function createDefaultTrajectoryVisualLayerRegistry\(\): TrajectoryVisualLayerRegistry/);
  assert.match(source, /function resolveTrajectoryVisualLayer/);
  assert.match(source, /function normalizeVisualLayerClassId\(id: string\): string/);
  assert.match(source, /Unknown Local Work Trajectory \$\{kind\} visual layer/);
  assert.match(source, /requested by \$\{owner\}/);
  assert.match(source, /Known \$\{kind\} layers: \$\{knownLayerIds\}/);
  assert.match(source, /Register the missing layer in createDefaultTrajectoryVisualLayerRegistry\(\)/);
  assert.match(source, /'--pg-lwt-layer-z': layer\.zIndex/);
  assert.match(source, /function layeredNodeClassNames\(/);
  assert.match(source, /function layeredEdgeClassNames\(/);
  assert.match(source, /function eventNodeVisualLayer\(/);
  assert.match(source, /function relationEdgeVisualLayerId\(kind: string\): TrajectoryEdgeVisualLayerId/);
  for (const nodeLayer of ['lane', 'event', 'laneOpeningJunction', 'compoundProxy', 'compound', 'dependencyProxy', 'statusAttention', 'active', 'selected']) {
    assert.match(source, new RegExp(`\\{ kind: 'node', id: '${nodeLayer}', zIndex: [0-9]+ \\}`));
  }
  for (const edgeLayer of ['sequence', 'relianceOverlay', 'dependencyProxy', 'laneOpening', 'merge', 'relation']) {
    assert.match(source, new RegExp(`\\{ kind: 'edge', id: '${edgeLayer}', zIndex: [0-9]+ \\}`));
  }
  assert.match(source, /width: laneLabelWidth,[\s\S]*height: laneLabelHeight,/);
  assert.match(source, /width: nodeWidth,[\s\S]*height: nodeHeight,/);
  assert.match(source, /<MiniMap/);
  assert.match(source, /const \[isMiniMapCollapsed, setIsMiniMapCollapsed\] = useState\(false\);/);
  assert.match(source, /querySelectorAll<HTMLElement>\('\[data-pg-trajectory-payload-id\]'\)/);
  assert.match(source, /function mountTrajectory\(mount: HTMLElement\): void/);
  assert.match(source, /mount\.dataset\.pgTrajectoryPayloadId/);
  assert.match(source, /\{isMiniMapCollapsed \? null : \(/);
  assert.match(source, /width=\{190\}/);
  assert.match(source, /height=\{128\}/);
  assert.match(source, /bgColor="rgba\(255, 250, 240, 0\.96\)"/);
  assert.match(source, /nodeStrokeColor=\{\(node\) => \(node\.id\.startsWith\('lane:'\) \? '#254b65' : '#51677a'\)\}/);
  assert.match(source, /maskStrokeColor="rgba\(49, 95, 126, 0\.46\)"/);
  assert.match(source, /className="pg-lwt-minimap-toggle"/);
  assert.match(source, /aria-expanded=\{!isMiniMapCollapsed\}/);
  assert.match(source, /data-pg-minimap-collapsed=\{isMiniMapCollapsed \? 'true' : 'false'\}/);
  assert.match(source, /setIsMiniMapCollapsed\(\(current\) => !current\)/);
  assert.match(source, /\{isMiniMapCollapsed \? 'Show map' : 'Hide map'\}/);
  assert.match(source, /const orderedLanes = laneOrderOverride \?\? orderLanes\(trajectory, lanes, events, relations\);/);
  assert.match(source, /const \[laneOrderOverride, setLaneOrderOverride\] = useState<string\[\] \| null>\(null\);/);
  assert.match(source, /const manualLaneOrder = useMemo\(/);
  assert.match(source, /function applyLaneOrderOverride\(lanes: TrajectoryLane\[\], laneOrderOverride: string\[\]\): TrajectoryLane\[\]/);
  assert.match(source, /function moveLaneInOrder\(/);
  assert.match(source, /function buildLaneRelationWeights\(/);
  assert.match(source, /function compareLaneSiblings\(/);
  assert.match(source, /const relationWeightedLaneOrderKinds = new Set\(\[/);
  assert.match(source, /relationWeightedLaneOrderKinds\.has\(relation\.kind\)/);
  assert.match(source, /totalLaneRelationWeight/);
  assert.match(source, /Move lane up/);
  assert.match(source, /Move lane down/);
  assert.match(source, /pg-lwt-lane-order-controls/);
  assert.match(source, /refresh resets to relation-weighted order/);
  assert.match(source, /fitMode: 'all' \| 'focus';/);
  assert.match(source, /layout\.fitMode === 'all'/);
  assert.match(source, /const initialViewport = shouldFitEntireGraph[\s\S]*buildTopAlignedViewport\(layout\.nodes, activeNode\)[\s\S]*buildFocusedViewport\(activeNode\);/);
  assert.match(source, /defaultViewport=\{initialViewport\}/);
  assert.match(source, /Math\.min\(fullFitTargetWidth \/ graphWidth, fullFitTargetHeight \/ graphHeight\)/);
  assert.match(source, /isSchedulerStateProjection\(trajectory\) \? 'all' : 'focus'/);
  assert.match(source, /function isSchedulerStateProjection\(trajectory: LocalWorkTrajectory \| null\): boolean/);
  assert.match(source, /trajectory\?\.metadata\?\.projection === 'scheduler-state'/);
  assert.match(source, /function orderSchedulerProjectionLanes\(/);
  assert.match(source, /firstEventOrderByLaneId/);
  assert.match(source, /Lane-first layout orders scheduler projection lanes by earliest projected task order\./);
  assert.doesNotMatch(source, /lanes\.slice\(\)\.sort\(\(left, right\) => left\.id\.localeCompare\(right\.id\)\)/);
  assert.match(source, /function orderLanes\(\s*trajectory: LocalWorkTrajectory \| null,/);
  assert.match(source, /laneOpeningRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /childLaneIds\.add\(opening\.childLaneId\)/);
  assert.match(source, /childrenByParent\.get\(laneId\) \?\? \[\]/);
  assert.match(source, /function compareLaneRoots\(left: TrajectoryLane, right: TrajectoryLane\): number/);
  assert.match(source, /left\.id === 'lane:main' \? 0 : 1/);
  assert.match(source, /function computeEventColumns\(/);
  assert.match(source, /function computeLaneStartColumns\(/);
  assert.match(source, /function raiseColumnAtLeast\(/);
  assert.match(source, /const maxColumnConstraintPasses = 80;/);
  assert.match(source, /function buildLaneLayout\(/);
  assert.match(source, /setLayout\(buildFallbackLayout\(/);
  assert.match(source, /function buildFallbackLayout\(/);
  assert.match(source, /const isEmptyLifecycle = Boolean\(/);
  assert.match(source, /metadata\?\.lifecycle_state === 'empty'/);
  assert.match(source, /The agent will create the first lane and active event when it starts a tracked task\./);
  assert.match(source, /activeEventId: string \| null;/);
  assert.match(source, /focusEventId: string \| null;/);
  assert.match(source, /type RelationBadge = \{/);
  assert.match(source, /external\?: boolean;/);
  assert.match(source, /type TrajectoryDetail = \{/);
  assert.match(source, /relation: TrajectoryRelation \| null;/);
  assert.match(source, /externalRelianceIndicators: ExternalRelianceIndicator\[\];/);
  assert.match(source, /dependencyProxy: DependencyProxy \| null;/);
  assert.match(source, /type DependencyProxy = \{/);
  assert.match(source, /type DependencyProxyPlacement = \{/);
  assert.match(source, /type LaneOpeningFanout = \{/);
  assert.match(source, /type NavigationSnapshot = \{/);
  assert.match(source, /type EndpointTarget = \{/);
  assert.match(source, /type RelationTarget = \{/);
  assert.match(source, /const \[trajectoryStack, setTrajectoryStack\] = useState<LocalWorkTrajectory\[\]>\(\[\]\);/);
  assert.match(source, /const currentTrajectory = trajectoryStack\.at\(-1\) \?\? trajectory;/);
  assert.match(source, /const \[selectedRelationId, setSelectedRelationId\] = useState<string \| null>\(null\);/);
  assert.match(source, /const \[selectedProxyId, setSelectedProxyId\] = useState<string \| null>\(null\);/);
  assert.match(source, /const \[navigationHistory, setNavigationHistory\] = useState<NavigationSnapshot\[\]>\(\[\]\);/);
  assert.match(source, /const dependencyProxies = useMemo\(/);
  assert.match(source, /buildDependencyProxies\(trajectory, currentTrajectory, relations, events, childTrajectoryById\)/);
  assert.match(source, /selectedProxyId,/);
  assert.match(source, /type PendingEndpointSelection = \{/);
  assert.match(source, /const \[pendingSelectedEventId, setPendingSelectedEventId\] = useState<PendingEndpointSelection \| null>\(null\);/);
  assert.match(source, /type PendingRelationSelection = \{/);
  assert.match(source, /const \[pendingSelectedRelationId, setPendingSelectedRelationId\] = useState<PendingRelationSelection \| null>\(null\);/);
  assert.match(source, /type ExternalRelianceIndicator = \{/);
  assert.match(source, /function buildChildTrajectoryIndex\(trajectory: LocalWorkTrajectory \| null\): Map<string, LocalWorkTrajectory>/);
  assert.match(source, /for \(const child of candidate\.childTrajectories \?\? \[\]\)/);
  assert.match(source, /function buildSelectedDetail\(/);
  assert.match(source, /childTrajectory: childTrajectoryById\.get\(childTrajectoryId\) \?\? null/);
  assert.match(source, /function buildExternalRelianceByEventId\(/);
  assert.match(source, /collectExternalRelianceEndpoint\(indicatorsByEventId, currentTrajectory, ownerTrajectory, relation, 'source'\)/);
  assert.match(source, /source_endpoint_trajectory_id/);
  assert.match(source, /target_endpoint_trajectory_id/);
  assert.match(source, /function TrajectoryBreadcrumb\(/);
  assert.match(source, /return \[trajectory, \.\.\.trajectoryStack\];/);
  assert.match(source, /aria-label="Trajectory breadcrumb"/);
  assert.match(source, /canGoBack: boolean;/);
  assert.match(source, /canGoUp: boolean;/);
  assert.match(source, /className="pg-lwt-breadcrumb-back"/);
  assert.match(source, /title="Back to previous path"/);
  assert.match(source, /className="pg-lwt-breadcrumb-up"/);
  assert.match(source, /title="Go to parent path"/);
  assert.match(source, /setTrajectoryStack\(\(current\) => current\.slice\(0, -1\)\)/);
  assert.match(source, /const handleBack = \(\): void => \{/);
  assert.match(source, /setNavigationHistory\(\(current\) => \{/);
  assert.match(source, /setTrajectoryStack\(previous\.trajectoryStack\)/);
  assert.match(source, /setSelectedProxyId\(previous\.selectedProxyId\)/);
  assert.match(source, /function TrajectoryDetailPanel\(/);
  assert.match(source, /Child trajectory/);
  assert.match(source, /Enter child/);
  assert.match(source, /Dependency proxy/);
  assert.match(source, /Depended precise endpoint/);
  assert.match(source, /Open owner relation/);
  assert.match(source, /onEnterChild\(childTrajectory\)/);
  assert.match(source, /function ExternalRelianceCard\(/);
  assert.match(source, /External reliance/);
  assert.match(source, /Open parent relation/);
  assert.match(source, /function collectExternalRelianceEndpoint\(/);
  assert.match(source, /function buildDependencyProxies\(/);
  assert.match(source, /function buildDependencyProxyPlacements\(/);
  assert.match(source, /function buildDependencyProxyNode\(placement: DependencyProxyPlacement\): Node/);
  assert.match(source, /function buildDependencyProxyEdge\(placement: DependencyProxyPlacement\): Edge/);
  assert.match(source, /function buildLaneOpeningFanouts\(/);
  assert.match(source, /function buildLaneOpeningJunctionNode\(fanout: LaneOpeningFanout\): Node/);
  assert.match(source, /function buildLaneOpeningFanoutEdges\(fanout: LaneOpeningFanout\): Edge\[\]/);
  assert.doesNotMatch(source, /label: 'needed'/);
  assert.match(source, /function findEndpointTrajectory\(/);
  assert.match(source, /function dependencyProxyId\(relation: TrajectoryRelation, endpointRole: string\): string/);
  assert.match(source, /function isEventNode\(node: Node\): boolean/);
  assert.match(source, /function isDependencyProxyNode\(node: Node\): boolean/);
  assert.match(source, /onNodeClick=\{\(_, node\) => \{/);
  assert.match(source, /if \(isDependencyProxyNode\(node\)\) \{/);
  assert.match(source, /onSelectProxy\(node\.id\);/);
  assert.match(source, /onEdgeClick=\{\(_, edge\) => \{/);
  assert.match(source, /isRelationEdge\(edge\) \? relationIdFromEdgeId\(edge\.id\) : null/);
  assert.match(source, /onPaneClick=\{\(\) => \{/);
  assert.match(source, /selected: node\.id === selectedEventId \|\| node\.id === selectedProxyId/);
  assert.match(source, /className: trajectoryNodeClassNameForSelection\(node, selectedEventId, selectedProxyId, layout\.nodes\)/);
  assert.match(source, /style: trajectoryNodeStyleForSelection\(node, selectedEventId, selectedProxyId\)/);
  assert.match(source, /function trajectoryNodeClassNameForSelection\(/);
  assert.match(source, /nodeVisualLayer\('selected', 'TrajectoryFlow\.selectedNode'\)/);
  assert.match(source, /selected: isRelationEdge\(edge\)[\s\S]*relationIdFromEdgeId\(edge\.id\) === selectedRelationId/);
  assert.match(source, /function isSelectedCompoundGroupNode\(node: Node, selectedEventId: string \| null, nodes: Node\[\]\): boolean/);
  assert.match(source, /'pg-lwt-node-compound-group-selected'/);
  assert.match(source, /node\.data\?\.childTrajectoryId === selectedChildTrajectoryId/);
  assert.match(source, /function findActiveEventId\(/);
  assert.match(source, /function findFocusEventId\(/);
  assert.match(source, /'blocked', 'waiting', 'pending', 'completed', 'archived'/);
  assert.match(source, /event\.status === 'in_progress'/);
  assert.match(source, /event\.kind === 'compound'/);
  assert.match(source, /childTrajectoryId = event\.metadata\.child_trajectory_id/);
  assert.match(source, /const compoundMode = event\.metadata\.compound_mode \?\? '';/);
  assert.match(source, /const compoundRole = event\.metadata\.compound_role \?\? '';/);
  assert.match(source, /function buildChildEventCountByTrajectoryId\(events: TrajectoryEvent\[\]\): Map<string, number>/);
  assert.match(source, /packed_event_ids/);
  assert.match(source, /isActive \? 'pg-lwt-node-active' : ''/);
  assert.match(source, /isCompound \? 'pg-lwt-node-compound' : ''/);
  assert.match(source, /const layer = eventNodeVisualLayer\(isActive, normalizedStatus, isCompound, compoundRole\);/);
  assert.match(source, /className: layeredNodeClassNames\(layer, \[/);
  assert.match(source, /pg-lwt-node-compound-role-\$\{normalizeStatus\(compoundRole\)\}/);
  assert.match(source, /pg-lwt-node-status-\$\{normalizedStatus\}/);
  assert.match(source, /data-pg-event-active=\{isActive \? 'true' : 'false'\}/);
  assert.match(source, /data-pg-child-trajectory-id=\{childTrajectoryId\}/);
  assert.match(source, /data-pg-compound-role=\{compoundRole\}/);
  assert.match(source, /childTrajectoryId,/);
  assert.match(source, /compoundRole,/);
  assert.match(source, /pg-lwt-compound-kicker/);
  assert.match(source, /Compound · \$\{compoundMode\}/);
  assert.match(source, /compoundEventBorder\(compoundRole\)/);
  assert.match(source, /compoundEventBackground\(event\.status\)/);
  assert.match(source, /data-pg-lane-status=\{lane\.status\}/);
  assert.match(source, /function laneBackground\(/);
  assert.match(source, /function eventBackground\(/);
  assert.match(source, /setViewport\(buildFocusedViewport\(activeNode\), \{ duration: 180 \}\);/);
  assert.match(source, /function buildFocusedViewport\(/);
  assert.match(source, /setViewport\(buildTopAlignedViewport\(layout\.nodes, activeNode\), \{ duration: 0 \}\);/);
  assert.match(source, /function buildTopAlignedViewport\(nodes: Node\[\], activeNode: Node \| undefined\)/);
  assert.match(source, /const graphHeight = Math\.max\(1, bounds\.maxY - bounds\.minY\);/);
  assert.match(source, /Math\.min\(fullFitTargetWidth \/ graphWidth, fullFitTargetHeight \/ graphHeight\)/);
  assert.match(source, /x: Math\.max\(42, 110 - \(bounds\.minX \* zoom\)\)/);
  assert.match(source, /y: 72 - \(bounds\.minY \* zoom\)/);
  assert.match(source, /x: \(-activeNode\.position\.x \* zoom\) \+ 300/);
  assert.match(source, /node\.id === layout\.activeEventId/);
  assert.doesNotMatch(source, /buildWrappedLayout/);
  assert.doesNotMatch(source, /readableWrapThreshold/);
  assert.doesNotMatch(source, /wrappedColumns/);
  assert.match(source, /data-pg-lwt-layout-mode=\{layout\.mode\}/);
  assert.match(source, /const alignmentRelationKinds = new Set\(\[/);
  const alignmentSetSource = source.match(/const alignmentRelationKinds = new Set\(\[[\s\S]*?\]\);/)?.[0] ?? '';
  assert.match(alignmentSetSource, /'proposes_new_line'/);
  assert.match(alignmentSetSource, /'approves_new_line'/);
  assert.match(alignmentSetSource, /'merges_into'/);
  assert.doesNotMatch(alignmentSetSource, /'depends_on'/);
  assert.doesNotMatch(alignmentSetSource, /'waits_for'/);
  assert.doesNotMatch(alignmentSetSource, /'syncs_from'/);
  assert.match(source, /alignmentRelationKinds\.has\(relation\.kind\)[\s\S]*raiseColumnAtLeast\(columns, target\.id, sourceColumn \+ 1\)/);
  assert.match(source, /'merges_into'/);
  assert.match(source, /raiseColumnAtLeast\(columns, source\.id, targetColumn - 1\)/);
  assert.match(source, /const laneOpeningRelationKinds = new Set\(\[/);
  assert.match(source, /laneOpeningRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /laneStartColumns\.set\(target\.laneId, eventColumns\.get\(source\.id\) \?\? 0\)/);
  assert.match(source, /x: laneXForColumn\(startColumn\)/);
  assert.match(source, /x: eventXForColumn\(eventColumn\)/);
  assert.match(source, /const auxiliaryRelationKinds = new Set\(\[/);
  const auxiliarySetSource = source.match(/const auxiliaryRelationKinds = new Set\(\[[\s\S]*?\]\);/)?.[0] ?? '';
  assert.match(auxiliarySetSource, /'proposes_new_line'/);
  assert.match(auxiliarySetSource, /'approves_new_line'/);
  assert.match(source, /const relianceRelationKinds = new Set\(\[/);
  const relianceSetSource = source.match(/const relianceRelationKinds = new Set\(\[[\s\S]*?\]\);/)?.[0] ?? '';
  assert.match(relianceSetSource, /'depends_on'/);
  assert.match(relianceSetSource, /'waits_for'/);
  assert.match(relianceSetSource, /'syncs_from'/);
  assert.doesNotMatch(relianceSetSource, /'unblocks'/);
  assert.doesNotMatch(relianceSetSource, /'hands_off'/);
  assert.doesNotMatch(relianceSetSource, /'merges_into'/);
  assert.doesNotMatch(relianceSetSource, /'proposes_new_line'/);
  assert.doesNotMatch(relianceSetSource, /'approves_new_line'/);
  assert.doesNotMatch(source, /const sidePortRelationKinds = new Set\(\[/);
  assert.match(source, /Handle,/);
  assert.match(source, /const relianceTopSourceHandle = 'reliance-top-source';/);
  assert.match(source, /const relianceTopTargetHandle = 'reliance-top-target';/);
  assert.match(source, /const relianceBottomSourceHandle = 'reliance-bottom-source';/);
  assert.match(source, /const relianceBottomTargetHandle = 'reliance-bottom-target';/);
  assert.match(source, /const mainFlowSourceHandle = 'main-flow-source';/);
  assert.match(source, /const mainFlowTargetHandle = 'main-flow-target';/);
  assert.doesNotMatch(source, /const auxiliaryTopSourceHandle = 'aux-top-source';/);
  assert.doesNotMatch(source, /const auxiliaryTopTargetHandle = 'aux-top-target';/);
  assert.doesNotMatch(source, /const auxiliaryBottomSourceHandle = 'aux-bottom-source';/);
  assert.doesNotMatch(source, /const auxiliaryBottomTargetHandle = 'aux-bottom-target';/);
  assert.doesNotMatch(source, /function AuxiliaryRelationHandles\(\): React\.ReactElement/);
  assert.doesNotMatch(source, /function LaneRelationHandles\(\): React\.ReactElement/);
  assert.doesNotMatch(source, /<LaneRelationHandles \/>/);
  assert.doesNotMatch(source, /<AuxiliaryRelationHandles \/>/);
  assert.match(source, /function MainFlowHandles\(\): React\.ReactElement/);
  assert.match(source, /<MainFlowHandles \/>/);
  assert.match(source, /function RelianceOverlayHandles\(\): React\.ReactElement/);
  assert.match(source, /<RelianceOverlayHandles \/>/);
  assert.match(source, /function buildRelationBadgesByEventId\(/);
  assert.match(source, /const relationBadgesByEventId = buildRelationBadgesByEventId\(relations, eventById, externalRelianceByEventId\);/);
  assert.match(source, /const dependencyProxyPlacements = buildDependencyProxyPlacements\(dependencyProxies, eventColumns, eventLaneIndexById\);/);
  assert.match(source, /const laneOpeningFanouts = buildLaneOpeningFanouts\(relations, eventById, eventColumns, eventLaneIndexById, eventIds\);/);
  assert.match(source, /const laneOpeningNodes = laneOpeningFanouts\.map\(\(fanout\) => buildLaneOpeningJunctionNode\(fanout\)\);/);
  assert.match(source, /const laneOpeningEdges = laneOpeningFanouts\.flatMap\(\(fanout\) => buildLaneOpeningFanoutEdges\(fanout\)\);/);
  assert.match(source, /nodes\.push\(\.\.\.dependencyProxyPlacements\.map\(\(placement\) => buildDependencyProxyNode\(placement\)\)\);/);
  assert.match(source, /const dependencyProxyEdges = dependencyProxyPlacements\.map\(\(placement\) => buildDependencyProxyEdge\(placement\)\);/);
  assert.match(source, /nodes: \[\.\.\.nodes, \.\.\.laneOpeningNodes\]/);
  assert.match(source, /\.\.\.relationEdges, \.\.\.laneOpeningEdges, \.\.\.relianceEdges, \.\.\.dependencyProxyEdges/);
  assert.match(source, /data-pg-dependency-proxy-id=\{proxy\.id\}/);
  assert.match(source, /data-pg-dependent-event-id=\{proxy\.dependentEventId\}/);
  assert.match(source, /const dependencyProxyTopSourceHandle = 'dependency-proxy-top-source';/);
  assert.match(source, /const dependencyProxyBottomSourceHandle = 'dependency-proxy-bottom-source';/);
  assert.match(source, /const layer = nodeVisualLayer\('dependencyProxy', 'buildDependencyProxyNode'\);/);
  assert.match(source, /sourceHandle: placement\.side === 'top' \? dependencyProxyBottomSourceHandle : dependencyProxyTopSourceHandle/);
  assert.match(source, /targetHandle: placement\.side === 'top' \? relianceTopTargetHandle : relianceBottomTargetHandle/);
  assert.match(source, /'pg-lwt-edge-dependency-proxy'/);
  assert.match(source, /'pg-lwt-node-dependency-proxy'/);
  assert.match(source, /laneOpeningSourceRelations\.set\(source\.id, sourceRelations\)/);
  assert.match(source, /badges\.push\(laneOpeningSourceBadge\(sourceRelations\)\)/);
  assert.match(source, /appendRelationBadge\(badgesByEventId, relation, target, source, 'target'\)/);
  assert.match(source, /label: externalRelianceBadgeLabel\(indicator\)/);
  assert.match(source, /external: true/);
  assert.match(source, /tone: 'external'/);
  assert.match(source, /!auxiliaryRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /relationBadgesByEventId\.get\(event\.id\) \?\? \[\]/);
  assert.match(source, /className="pg-lwt-relation-badges"/);
  assert.match(source, /pg-lwt-relation-badge-external/);
  assert.match(source, /pg-lwt-relation-badge-\$\{badge\.tone\}/);
  assert.match(source, /pg-lwt-node-external-reliance/);
  assert.match(source, /data-pg-external-reliance=\{hasExternalReliance \? 'true' : 'false'\}/);
  assert.doesNotMatch(source, /id=\{auxiliaryTopSourceHandle\}[\s\S]*position=\{Position\.Top\}/);
  assert.doesNotMatch(source, /id=\{auxiliaryBottomTargetHandle\}[\s\S]*position=\{Position\.Bottom\}/);
  assert.doesNotMatch(source, /className="pg-lwt-aux-handle"/);
  assert.match(source, /id=\{relianceTopSourceHandle\}[\s\S]*position=\{Position\.Top\}/);
  assert.match(source, /id=\{relianceBottomTargetHandle\}[\s\S]*position=\{Position\.Bottom\}/);
  assert.match(source, /id=\{mainFlowSourceHandle\}[\s\S]*position=\{Position\.Right\}/);
  assert.match(source, /id=\{mainFlowTargetHandle\}[\s\S]*position=\{Position\.Left\}/);
  assert.match(source, /className="pg-lwt-main-flow-handle"/);
  assert.match(source, /className="pg-lwt-reliance-handle"/);
  assert.doesNotMatch(source, /sourcePosition: Position\.Right/);
  assert.doesNotMatch(source, /targetPosition: Position\.Left/);
  assert.match(source, /function buildEventLaneIndexById\(/);
  assert.match(source, /const eventLaneIndexById = buildEventLaneIndexById\(orderedLanes, eventsByLane\);/);
  assert.match(source, /function laneOpeningFanoutLabel\(fanout: LaneOpeningFanout\): string/);
  assert.match(source, /function laneOpeningJunctionId\(sourceEventId: string\): string/);
  assert.match(source, /function average\(values: number\[\]\): number/);
  assert.match(source, /function buildRelationEdge\(relation: TrajectoryRelation\): Edge/);
  assert.match(source, /\.map\(\(relation\) => buildRelationEdge\(relation\)\)/);
  const relationEdgeFunctionSource = source.slice(
    source.indexOf('function buildRelationEdge'),
    source.indexOf('function buildRelianceOverlayEdge'),
  );
  assert.doesNotMatch(source, /const visualDirection = visualRelationDirection\(relation\);/);
  assert.match(relationEdgeFunctionSource, /id: relationEdgeId\(relation\)/);
  assert.match(relationEdgeFunctionSource, /source: relation\.sourceEventId/);
  assert.match(relationEdgeFunctionSource, /target: relation\.targetEventId/);
  assert.match(relationEdgeFunctionSource, /interactionWidth: relation\.kind === 'depends_on' && dependencyScope\(relation\) === 'inner' \? 22 : 14/);
  assert.match(relationEdgeFunctionSource, /pg-lwt-edge-projection-\$\{normalizeStatus\(projection\)\}/);
  assert.match(source, /sourceHandle: mainFlowSourceHandle/);
  assert.match(source, /targetHandle: mainFlowTargetHandle/);
  assert.doesNotMatch(source, /function sidePortRelationHandles\(/);
  assert.match(source, /type: 'smoothstep'/);
  assert.match(source, /markerEnd: \{/);
  assert.doesNotMatch(source, /function visualRelationDirection\(relation: TrajectoryRelation\)/);
  assert.doesNotMatch(source, /laneOpeningRelationKinds\.has\(relation\.kind\)[\s\S]*target: target\.laneId/);
  assert.doesNotMatch(source, /source: relation\.targetEventId[\s\S]*target: relation\.sourceEventId/);
  assert.match(source, /const relianceEdges = relations[\s\S]*relianceRelationKinds\.has\(relation\.kind\)[\s\S]*buildRelianceOverlayEdge\(relation, eventLaneIndexById\)/);
  assert.match(source, /edges: \[\.\.\.sequenceEdges, \.\.\.relationEdges, \.\.\.laneOpeningEdges, \.\.\.relianceEdges, \.\.\.dependencyProxyEdges\]/);
  assert.match(source, /function buildRelianceOverlayEdge\(/);
  assert.match(source, /id: relationEdgeId\(relation, ':reliance-overlay'\)/);
  assert.match(source, /sourceHandle: handles\.sourceHandle/);
  assert.match(source, /targetHandle: handles\.targetHandle/);
  assert.match(source, /interactionWidth: relation\.kind === 'depends_on' && dependencyScope\(relation\) === 'inner' \? 22 : 14/);
  assert.match(source, /'pg-lwt-edge-reliance-overlay'/);
  assert.match(source, /pg-lwt-edge-projection-\$\{normalizeStatus\(projection\)\}/);
  assert.match(source, /function relianceOverlayHandles\(/);
  assert.match(source, /sourceHandle: relianceBottomSourceHandle[\s\S]*targetHandle: relianceTopTargetHandle/);
  assert.match(source, /sourceHandle: relianceTopSourceHandle[\s\S]*targetHandle: relianceBottomTargetHandle/);
  assert.match(source, /const relationStyle = edgeStyleForKind\(kind\);/);
  assert.match(source, /const layer = edgeVisualLayer\('sequence', 'buildFlowEdge'\);/);
  assert.match(source, /label: isSequence \? undefined : relationStyle\.label/);
  assert.match(source, /function edgeStyleForKind\(kind: string\)/);
  assert.match(source, /function projectionStrokeDasharray\(projection: string, fallback: string \| undefined\): string/);
  assert.match(source, /case 'cross-compound':[\s\S]*return '10 4 2 4'/);
  assert.match(source, /case 'cross-boundary':[\s\S]*return '7 4'/);
  assert.match(source, /const relationEdgeIdPrefix = 'relation:';/);
  assert.match(source, /function relationStableId\(relation: TrajectoryRelation\): string/);
  assert.match(source, /function relationEdgeId\(relation: TrajectoryRelation, suffix = ''\): string/);
  assert.match(source, /function relationIdFromEdgeId\(edgeId: string\): string \| null/);
  assert.match(source, /function RelationEndpointCard\(/);
  assert.match(source, /relationPreciseEndpointLabel\(relation\.kind, 'source'\)/);
  assert.match(source, /relationPreciseEndpointLabel\(relation\.kind, 'target'\)/);
  assert.match(source, /Jump to endpoint/);
  assert.match(source, /source_endpoint_trajectory_id/);
  assert.match(source, /target_endpoint_trajectory_id/);
  assert.match(source, /function endpointMetadataRows\(prefix: 'source' \| 'target', metadata: Record<string, string>\): \[string, string\]\[\]/);
  assert.match(source, /function findTrajectoryPath\(root: LocalWorkTrajectory, trajectoryId: string\): LocalWorkTrajectory\[\]/);
  assert.match(source, /function formatEventReference\(event: TrajectoryEvent \| null, fallbackEventId: string\): string/);
  assert.match(source, /function relationGraphLabel\(relation: TrajectoryRelation\): string/);
  assert.match(source, /return dependencyScope\(relation\) === 'inner' \? '' : 'node dep'/);
  assert.match(source, /label: label \|\| undefined/);
  assert.match(source, /function relationEndpointRoleLabel\(kind: string, endpointRole: 'source' \| 'target'\): string/);
  assert.match(source, /return endpointRole === 'source' \? 'Provider' : 'Dependent'/);
  assert.match(source, /function relationEndpointBadgeLabel\(/);
  assert.match(source, /required by #\$\{relatedEvent\.order\}/);
  assert.match(source, /depends on #\$\{relatedEvent\.order\}/);
  assert.match(source, /case 'proposes_new_line':[\s\S]*'starts lane'/);
  assert.match(source, /case 'approves_new_line':[\s\S]*'approves lane'/);
  assert.match(source, /Dependency scope/);
  assert.match(source, /case 'depends_on':[\s\S]*label: 'depends'/);
  assert.match(source, /case 'proposes_new_line':[\s\S]*label: 'starts lane'/);
  assert.match(source, /case 'waits_for':[\s\S]*label: 'waits'/);
  assert.match(source, /case 'unblocks':[\s\S]*label: 'unblocks'/);
  assert.match(source, /case 'hands_off':[\s\S]*label: 'handoff'/);
  assert.match(source, /case 'syncs_from':[\s\S]*label: 'sync'/);
  assert.match(source, /case 'approves_new_line':[\s\S]*label: 'approved'/);
  assert.match(source, /className: layeredEdgeClassNames\(layer, \[[\s\S]*`pg-lwt-edge-\$\{normalizeStatus\(kind\)\}`/);
  assert.match(source, /className: layeredEdgeClassNames\(layer, \[[\s\S]*`pg-lwt-edge-\$\{normalizeStatus\(relation\.kind\)\}`/);
  assert.match(source, /relation\.kind !== 'sequence'[\s\S]*!auxiliaryRelationKinds\.has\(relation\.kind\)[\s\S]*!laneOpeningRelationKinds\.has\(relation\.kind\)/);
  assert.match(source, /return 'merge';/);
  assert.match(source, /return 'laneOpening';/);
  assert.match(source, /strokeDasharray: isSequence \? undefined : relationStyle\.strokeDasharray/);
});

test('local work trajectory stylesheet gives React Flow a stable drawing area', () => {
  const style = readFileSync(stylePath, 'utf-8');

  assert.match(style, /\.pg-lwt-shell \{[\s\S]*height: var\(--pg-lwt-shell-height, clamp\(560px, 72vh, 900px\)\);/);
  assert.match(style, /\.pg-lwt-shell \{[\s\S]*min-height: var\(--pg-lwt-shell-min-height, clamp\(520px, 64vh, 840px\)\);/);
  assert.match(style, /\.pg-lwt-workspace \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(260px, 320px\);/);
  assert.match(style, /\.pg-lwt-flow \{[\s\S]*height: 100%;/);
  assert.match(style, /\.pg-lwt-flow \.react-flow \{[\s\S]*height: 100%;/);
  assert.match(style, /linear-gradient\(90deg, rgba\(49, 95, 126, 0\.08\) 0 170px/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__minimap \{[\s\S]*margin: 0 16px 92px 0;/);
  assert.match(style, /\.pg-lwt-minimap-toggle \{[\s\S]*right: 16px;[\s\S]*bottom: 92px;/);
  assert.match(style, /\.pg-lwt-minimap-toggle:hover,/);
  assert.doesNotMatch(style, /\.pg-lwt-minimap-toggle\[data-pg-minimap-collapsed="true"\] \{[\s\S]*bottom:/);
  assert.match(style, /\.pg-lwt-layout-note/);
  assert.match(style, /\.pg-lwt-lane-node-head/);
  assert.match(style, /\.pg-lwt-lane-order-controls/);
  assert.match(style, /\.pg-lwt-lane-order-controls button:disabled/);
  assert.match(style, /\.pg-lwt-breadcrumb-back/);
  assert.match(style, /\.pg-lwt-breadcrumb-up/);
  assert.match(style, /\.pg-lwt-breadcrumb-back:disabled/);
  assert.match(style, /\.pg-lwt-breadcrumb-up:disabled/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-lane,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-lane-opening-junction,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-compound-proxy,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-dependency-proxy,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-status-attention,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-active,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-layer-node-selected \{/);
  assert.match(style, /z-index: var\(--pg-lwt-layer-z, 4\);/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-compound/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-compound-role-proxy/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-compound-group-selected \.pg-lwt-event-node/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.selected \.pg-lwt-event-node/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-dependency-proxy/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-dependency-proxy\.selected \.pg-lwt-dependency-proxy-node/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-dependency-proxy-external \.pg-lwt-dependency-proxy-node/);
  assert.match(style, /\.pg-lwt-compound-kicker/);
  assert.match(style, /\.pg-lwt-dependency-proxy-node/);
  assert.match(style, /\.pg-lwt-dependency-proxy-kicker/);
  assert.match(style, /\.pg-lwt-breadcrumb/);
  assert.match(style, /\.pg-lwt-detail/);
  assert.match(style, /\.pg-lwt-child-card/);
  assert.match(style, /\.pg-lwt-endpoint-card/);
  assert.match(style, /\.pg-lwt-enter-child/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-active="true"\] strong/);
  assert.match(style, /\.pg-lwt-relation-badges/);
  assert.match(style, /max-height: 42px;/);
  assert.match(style, /\.pg-lwt-relation-badge/);
  assert.match(style, /max-width: min\(100%, 152px\);/);
  assert.match(style, /\.pg-lwt-relation-badge-source/);
  assert.match(style, /\.pg-lwt-relation-badge-target/);
  assert.match(style, /\.pg-lwt-relation-badge-external/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-external-reliance \.pg-lwt-event-node/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-external-reliance::after/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-lane-opening-junction/);
  assert.match(style, /\.pg-lwt-lane-opening-junction-node/);
  assert.doesNotMatch(style, /\.pg-lwt-event-node \{[\s\S]*position: relative;/);
  assert.match(style, /\.pg-lwt-external-reliance-list/);
  assert.match(style, /\.pg-lwt-external-reliance-card/);
  assert.match(style, /\.pg-lwt-open-relation/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-status="waiting"\]/);
  assert.match(style, /\.pg-lwt-event-node\[data-pg-event-status="archived"\]/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__node\.pg-lwt-node-status-archived/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.pg-lwt-aux-handle/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__handle:not\(\.pg-lwt-main-flow-handle\):not\(\.pg-lwt-reliance-handle\):not\(\.pg-lwt-dependency-proxy-handle\) \{[\s\S]*opacity: 0;/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-main-flow-handle,/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-reliance-handle,/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-dependency-proxy-handle \{[\s\S]*opacity: 0;/);
  assert.match(style, /\.pg-lwt-flow \.pg-lwt-dependency-proxy-handle \{[\s\S]*pointer-events: none;/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-layer-edge-sequence,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-layer-edge-lane-opening,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-layer-edge-reliance-overlay,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-layer-edge-dependency-proxy,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-merges-into/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-merges-into \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-proposes-new-line/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-proposes-new-line \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-lane-opening-fanout \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-lane-opening-fanout \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-lane-opening-branch \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-reliance-overlay \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-dependency-proxy/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-dependency-proxy \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-dependency-proxy \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-dependency-scope-inner \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-dependency-scope-inner \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-projection-cross-boundary \.react-flow__edge-path,/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-projection-cross-compound \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.selected \.react-flow__edge-path/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-waits-for \.react-flow__edge-text/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-syncs-from \.react-flow__edge-text/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-auxiliary/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-side-port/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-auxiliary \.react-flow__edge-path/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-unblocks/);
  assert.doesNotMatch(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-hands-off/);
  assert.match(style, /\.pg-lwt-flow \.react-flow__edge\.pg-lwt-edge-approves-new-line/);
});
